export const chunk8 = [
  "  const half=span*MS_DAY/2;",
  "  const minCenter=LIFE_START+Math.min(half,(LIFE_END-LIFE_START)/2);",
  "  centerMs=clamp(centerMs,minCenter,LIFE_END);",
  "}",
  "",
  "function resize() {",
  "  const r=canvas.getBoundingClientRect();",
  "  const dpr=Math.min(window.devicePixelRatio||1,2.4);",
  "  canvas.width=Math.max(1,Math.round(r.width*dpr));",
  "  canvas.height=Math.max(1,Math.round(r.height*dpr));",
  "  ctx.setTransform(dpr,0,0,dpr,0,0);",
  "  draw();",
  "}",
  "",
  "function rr(x,y,w,h,r) {",
  "  r=Math.min(r,w/2,h/2);",
  "  ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);",
  "  ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();",
  "}",
  "",
  "function aggregatePerDay(a,b) {",
  "  const i0=clamp(Math.floor(a),0,TOTAL_DAYS), i1=clamp(Math.ceil(b),0,TOTAL_DAYS);",
  "  if(i1<=i0) return 0;",
  "  let n=0; for(let i=i0;i<i1;i++) n+=dayCounts[i];",
  "  return n/(i1-i0);",
  "}",
  "",
  "function densityBucket(level) {",
  "  return [60,7,1,1,1,null][level];",
  "}",
  "",
  "function drawDensity(level,startMs,endMs,w,axisY) {",
  "  const startDay=(startMs-LIFE_START)/MS_DAY;",
  "  const endDay=(endMs-LIFE_START)/MS_DAY;",
  "",
  "  if(level===5) {",
  "    const stacks=new Map();",
  "    for(const o of EVENT_OFFSETS) {",
  "      if(o<startDay || o>endDay) continue;",
  "      const x=((LIFE_START+o*MS_DAY-startMs)/(endMs-startMs))*w;",
  "      const slot=Math.floor(o*48);",
  "      const s=stacks.get(slot)||0; stacks.set(slot,s+1);",
  "      ctx.fillStyle=\"rgba(91,143,185,.88)\";",
  "      ctx.beginPath();ctx.arc(x,axisY-9-s*7,2.8,0,Math.PI*2);ctx.fill();",
  "    }",
  "    return;",
  "  }",
  "",
  "  const bucket=densityBucket(level);",
  "  const visible=endDay-startDay;",
  "  let bs=Math.floor(startDay/bucket)*bucket;",
  "  for(;bs<endDay;bs+=bucket) {",
  "    const be=bs+bucket;",
  "    const rate=aggregatePerDay(bs,be);",
  "    if(rate<=0) continue;",
  "    const intensity=1-Math.exp(-rate/(level===0?.055:.48));",
  "    const mid=(bs+be)/2;",
  "    const x=((LIFE_START+mid*MS_DAY-startMs)/(endMs-startMs))*w;",
  "    const bw=Math.max(level<2?2.2:3.2,bucket/visible*w*.64);",
  "    const bh=5+intensity*56;",
  "    ctx.fillStyle=`rgba(91,143,185,${(.24+intensity*.66).toFixed(3)})`;",
  "    rr(x-bw/2,axisY-bh,bw,bh,Math.min(4,bw/2));",
  "    ctx.fill();",
  "  }",
  "}",
  "",
  "",
  "function drawMemoryBeacons(level,startMs,endMs,w,axisY) {",
  "  const spanDays=(endMs-startMs)/MS_DAY;",
  "  const configs=[",
  "    {stem:8,width:1.8,alpha:.46,r:1.8},",
  "    {stem:13,width:2.4,alpha:.58,r:2.0},",
  "    {stem:20,width:3.0,alpha:.68,r:2.2},",
  "    {stem:27,width:3.5,alpha:.75,r:2.5},",
  "    {stem:34,width:4.0,alpha:.82,r:2.8},",
  "    {stem:0,width:0,alpha:0,r:0}",
  "  ];",
  "  if(level===5) return;",
  "",
  "  const c=configs[level];",
  "  for(const m of MEMORIES) {",
  "    if(m.ms<startMs || m.ms>endMs) continue;",
  "    const x=((m.ms-startMs)/(endMs-startMs))*w;",
  "",
  "    ctx.strokeStyle=`rgba(91,143,185,${c.alpha})`;",
  "    ctx.lineWidth=c.width;",
  "    ctx.lineCap=\"round\";",
  "    ctx.beginPath();",
  "    ctx.moveTo(x,axisY-3);",
  "    ctx.lineTo(x,axisY-c.stem);",
  "    ctx.stroke();",
  "",
  "    ctx.fillStyle=`rgba(91,143,185,${Math.min(.92,c.alpha+.12)})`;",
  "    ctx.beginPath();",
  "    ctx.arc(x,axisY-c.stem,c.r,0,Math.PI*2);",
  "    ctx.fill();",
  "  }",
  "}",
  "",
  "function tick(x,axisY,major,label=\"\",sub=\"\",strongSub=false) {",
  "  if(x<-55 || x>canvas.clientWidth+55) return;",
  "",
  "  ctx.strokeStyle=major?\"rgba(15,39,71,.66)\":\"rgba(62,74,89,.24)\";",
  "  ctx.lineWidth=major?1.5:1;",
  "  ctx.beginPath();",
  "  ctx.moveTo(x,axisY-(major?11:5));",
  "  ctx.lineTo(x,axisY+(major?10:5));",
  "  ctx.stroke();",
  "",
  "  if(major && label) {",
  "    ctx.textAlign=\"center\";",
  "    ctx.fillStyle=\"rgba(15,39,71,.90)\";",
  "    ctx.font=\"700 13px Inter,-apple-system,sans-serif\";",
  "    ctx.fillText(label,x,axisY+22);",
  "    if(sub) {",
  "      ctx.fillStyle=strongSub?\"rgba(15,39,71,.82)\":\"rgba(62,74,89,.58)\";",
  "      ctx.font=strongSub?\"650 11.5px Inter,-apple-system,sans-serif\":\"11px Inter,-apple-system,sans-serif\";",
  "      ctx.fillText(sub,x,axisY+34);",
  "    }",
  "  }",
  "}",
  "",
  "function drawLevel0(startMs,endMs,w,axisY) {",
  "  // 15 jaar: kleine marker ieder jaar; hoofdmarker iedere 5 jaar.",
  "  const first=Math.floor(ageAt(startMs));",
  "  const last=Math.ceil(ageAt(endMs));",
  "  for(let age=first;age<=last;age++) {",
  "    if(age<0 || age>60) continue;",
  "    const ms=LIFE_START+age*DAYS_YEAR*MS_DAY;",
  "    const x=((ms-startMs)/(endMs-startMs))*w;",
  "    const major=age%5===0;",
  "    tick(x,axisY,major,major?`${age} jaar`:\"\",major?String(new Date(ms).getFullYear()):\"\");",
  "  }",
  "}",
  "",
  "function drawLevel1(startMs,endMs,w,axisY) {",
  "  // 2 jaar: kleine marker per maand; hoofdmarker per kwartaal.",
  "  let d=new Date(startMs), y=d.getFullYear(), m=d.getMonth()-1;",
  "  for(let guard=0;guard<40;guard++) {",
  "    m++; if(m>11){m=0;y++}",
  "    const ms=new Date(y,m,1).getTime();",
  "    if(ms>endMs) break;",
  "    const major=m%3===0;",
  "    const x=((ms-startMs)/(endMs-startMs))*w;",
  "    tick(x,axisY,major,",
  "      major?new Date(ms).toLocaleDateString(\"nl-NL\",{month:\"short\"}):\"\",",
  "      major?String(y):\"\",",
  "      true",
  "    );",
  "  }",
  "}",
  "",
  "function drawLevel2(startMs,endMs,w,axisY) {",
  "  // 3 maanden: kleine marker per week; hoofdmarker per maand.",
  "  let month=new Date(new Date(startMs).getFullYear(),new Date(startMs).getMonth(),1);",
  "  while(month.getTime()<=endMs) {",
  "    const ms=month.getTime();",
  "    const x=((ms-startMs)/(endMs-startMs))*w;",
  "    tick(x,axisY,true,month.toLocaleDateString(\"nl-NL\",{month:\"short\"}),String(month.getFullYear()));",
  "    month=new Date(month.getFullYear(),month.getMonth()+1,1);",
  "  }",
  "  let monday=new Date(startMs);",
  "  monday.setHours(0,0,0,0);",
  "  monday.setDate(monday.getDate()-((monday.getDay()+6)%7));",
  "  for(let ms=monday.getTime();ms<=endMs;ms+=7*MS_DAY) {",
  "    const x=((ms-startMs)/(endMs-startMs))*w;",
  "    tick(x,axisY,false);",
  "  }",
  "}",
  "",
  "function drawLevel3(startMs,endMs,w,axisY) {",
  "  // 2 weken: marker per dag; hoofdmarker om de 2 dagen.",
  "  let d=new Date(startMs);",
  "  d=new Date(d.getFullYear(),d.getMonth(),d.getDate());",
  "  let i=0;",
  "  for(let ms=d.getTime();ms<=endMs;ms+=MS_DAY,i++) {",
  "    const x=((ms-startMs)/(endMs-startMs))*w;",
  "    const major=i%2===0;",
  "    const dt=new Date(ms);",
  "    tick(x,axisY,major,",
  "      major?dt.toLocaleDateString(\"nl-NL\",{weekday:\"short\",day:\"numeric\"}):\"\",",
  "      major?dt.toLocaleDateString(\"nl-NL\",{month:\"short\"}):\"\"",
  "    );",
  "  }",
  "}",
  "",
  "function drawLevel4(startMs,endMs,w,axisY) {",
  "  // 1 dag: grove dagindeling.",
  "  const s=new Date(startMs);",
  "  const dayStart=new Date(s.getFullYear(),s.getMonth(),s.getDate(),0,0,0,0).getTime();",
  "  const points=[",
  "    [dayStart,\"00:00\",\"nacht\"],",
  "    [dayStart+6*60*60*1000,\"06:00\",\"ochtend\"],",
  "    [dayStart+12*60*60*1000,\"12:00\",\"middag\"],",
  "    [dayStart+18*60*60*1000,\"18:00\",\"avond\"],",
  "    [dayStart+24*60*60*1000,\"24:00\",\"volgende dag\"]",
  "  ];",
  "  for(const [ms,label,sub] of points) {",
  "    const x=((ms-startMs)/(endMs-startMs))*w;",
  "    tick(x,axisY,true,label,sub);",
  "  }",
  "}",
  "",
  "function drawLevel5(startMs,endMs,w,axisY) {",
  "  // Dagdetail: halfuurmarker; hoofdmarker op ieder heel uur.",
  "  let d=new Date(startMs);",
  "  d.setSeconds(0,0);",
  "  d.setMinutes(d.getMinutes()<30?0:30);",
  "  for(let ms=d.getTime();ms<=endMs;ms+=30*60*1000) {",
  "    const dt=new Date(ms);",
  "    const major=dt.getMinutes()===0;",
  "    const x=((ms-startMs)/(endMs-startMs))*w;",
  "    tick(x,axisY,major,major?dt.toLocaleTimeString(\"nl-NL\",{hour:\"2-digit\",minute:\"2-digit\"}):\"\");",
  "  }",
  "}",
  "",
  "function drawScale(level,startMs,endMs,w,axisY) {",
  "  ctx.strokeStyle=\"rgba(91,143,185,.44)\";",
  "  ctx.lineWidth=1.2;",
  "  ctx.beginPath();ctx.moveTo(0,axisY+.5);ctx.lineTo(w,axisY+.5);ctx.stroke();",
  "",
  "  if(level===0) drawLevel0(startMs,endMs,w,axisY);",
  "  else if(level===1) drawLevel1(startMs,endMs,w,axisY);",
  "  else if(level===2) drawLevel2(startMs,endMs,w,axisY);",
  "  else if(level===3) drawLevel3(startMs,endMs,w,axisY);",
  "  else if(level===4) drawLevel4(startMs,endMs,w,axisY);",
  "  else drawLevel5(startMs,endMs,w,axisY);",
  "}",
  "",
  "function draw() {",
  "  const w=canvas.clientWidth,h=canvas.clientHeight;",
  "  if(!w || !h) return;",
  "  ctx.clearRect(0,0,w,h);",
  "",
  "  const [startMs,endMs]=bounds();",
  "  const axisY=h-64;",
  "  const level=activeLevel();",
  "",
  "  drawDensity(level,startMs,endMs,w,axisY);",
  "  drawMemoryBeacons(level,startMs,endMs,w,axisY);",
];
