export const chunk1 = [
  "<!doctype html>",
  "<html lang=\"nl\">",
  "<head>",
  "<meta charset=\"utf-8\">",
  "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,viewport-fit=cover,user-scalable=no\">",
  "<meta name=\"theme-color\" content=\"#FAFBFD\">",
  "<title>TALERA — Tijdlijnprototype v22 · PhotoBook</title>",
  "<style>",
  ":root {",
  "  --talera-deep:#0F2747;",
  "  --talera-soft:#5B8FB9;",
  "  --talera-light:#DCEAF6;",
  "  --talera-warm:#E7A98B;",
  "  --talera-neutral:#F7F4EF;",
  "  --talera-text:#3E4A59;",
  "  --talera-white:#FFFEFC;",
  "}",
  "* { box-sizing:border-box; -webkit-tap-highlight-color:transparent; }",
  "html,body {",
  "  margin:0;",
  "  width:100%;",
  "  height:100%;",
  "  overflow:hidden;",
  "  background:var(--talera-neutral);",
  "  color:var(--talera-deep);",
  "}",
  "body {",
  "  font-family:\"Avenir Next\",\"Helvetica Neue\",Inter,-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif;",
  "}",
  "button { font:inherit; }",
  "",
  ".app {",
  "  width:100%;",
  "  height:100dvh;",
  "  overflow:hidden;",
  "  display:grid;",
  "  grid-template-rows:minmax(0,1fr) 60px;",
  "  background:var(--talera-neutral);",
  "}",
  "",
  "",
  "",
  "main {",
  "  min-height:0;",
  "  height:100%;",
  "  overflow:hidden;",
  "  display:grid;",
  "  grid-template-rows:clamp(190px, 24dvh, 212px) minmax(0,1fr);",
  "  gap:0;",
  "}",
  ".timeline {",
  "  width:100%;",
  "  height:100%;",
  "  min-height:0;",
  "  position:relative;",
  "  overflow:hidden;",
  "  background:",
  "    linear-gradient(180deg,rgba(255,254,252,.98) 0%,rgba(220,234,246,.34) 100%);",
  "  border-top:1px solid rgba(15,39,71,.035);",
  "  border-bottom:1px solid rgba(15,39,71,.09);",
  "  touch-action:none;",
  "  user-select:none;",
  "}",
  "canvas { display:block; width:100%; height:100%; }",
  "",
  ".center-needle {",
  "  pointer-events:none;",
  "  position:absolute;",
  "  z-index:3;",
  "  left:50%;",
  "  top:8px;",
  "  bottom:8px;",
  "  width:2px;",
  "  transform:translateX(-1px);",
  "  background:linear-gradient(",
  "    180deg,",
  "    rgba(15,39,71,.05),",
  "    var(--talera-deep) 15%,",
  "    var(--talera-deep) 88%,",
  "    rgba(15,39,71,.05)",
  "  );",
  "}",
  ".center-needle::before {",
  "  content:\"\";",
  "  position:absolute;",
  "  left:50%; top:0;",
  "  width:10px; height:10px;",
  "  border-radius:50%;",
  "  transform:translate(-50%,-50%);",
  "  background:var(--talera-warm);",
  "  box-shadow:",
  "    0 0 0 4px rgba(231,169,139,.18),",
  "    0 0 0 7px rgba(91,143,185,.07);",
  "}",
  ".focus {",
  "  pointer-events:none;",
  "  position:absolute;",
  "  z-index:4;",
  "  left:50%;",
  "  top:15px;",
  "  transform:translateX(-50%);",
  "  padding:4px 10px;",
  "  border-radius:999px;",
  "  color:var(--talera-deep);",
  "  background:rgba(255,254,252,.94);",
  "  border:1px solid rgba(91,143,185,.18);",
  "  font-size:11px;",
  "  font-weight:650;",
  "  letter-spacing:.01em;",
  "  white-space:nowrap;",
  "}",
  "",
  "/* Photo/story stage remains intentionally content-empty in the zoom test. */",
  ".memory-space {",
  "  min-width:0;",
  "  min-height:0;",
  "  width:100%;",
  "  height:100%;",
  "  position:relative;",
  "  overflow:hidden;",
  "  margin:0;",
  "  border-radius:0;",
  "  border:0;",
  "  background:var(--talera-neutral);",
  "  box-shadow:none;",
  "}",
  ".memory-space::before {",
  "  content:\"\";",
  "  position:absolute;",
  "  inset:0;",
  "  pointer-events:none;",
  "  background:linear-gradient(",
  "    180deg,",
  "    rgba(15,39,71,0) 54%,",
  "    rgba(15,39,71,.05) 72%,",
  "    rgba(15,39,71,.18) 100%",
  "  );",
  "  z-index:2;",
  "}",
  ".placeholder {",
  "  position:absolute;",
  "  left:20px; right:20px; bottom:18px;",
  "  text-align:center;",
  "  font-size:10px;",
  "  letter-spacing:.04em;",
  "  color:rgba(62,74,89,.36);",
  "}",
  "",
  "/* Bottom navigation uses final TALERA hierarchy. */",
  "nav {",
  "  height:60px;",
  "  min-height:60px;",
  "  max-height:60px;",
  "  padding:4px 20px 4px;",
  "  display:grid;",
  "  grid-template-columns:1fr 1fr 1fr;",
  "  align-items:end;",
  "  border-top:1px solid rgba(15,39,71,.07);",
  "  background:rgba(247,244,239,.98);",
  "  backdrop-filter:blur(12px);",
  "  -webkit-backdrop-filter:blur(12px);",
  "  overflow:hidden;",
  "}",
  ".nav-item {",
  "  border:0;",
  "  background:transparent;",
  "  color:rgba(62,74,89,.58);",
  "  display:flex;",
  "  flex-direction:column;",
  "  align-items:center;",
  "  justify-content:flex-end;",
  "  gap:4px;",
  "  min-height:38px;",
  "  padding:0 0 2px;",
  "  font-size:10px;",
  "}",
  ".nav-item.active { color:var(--talera-deep); font-weight:650; }",
  ".timeline-icon { width:24px;height:17px;position:relative; }",
  ".timeline-icon::before {",
  "  content:\"\";position:absolute;left:1px;right:1px;top:8px;height:2px;border-radius:2px;background:currentColor;",
  "  box-shadow:-4px -4px 0 -.4px currentColor,4px 4px 0 -.4px currentColor;",
  "}",
  ".tell {",
  "  justify-self:center;",
  "  width:50px;height:50px;border:0;border-radius:50%;",
  "  color:var(--talera-white);",
  "  background:var(--talera-deep);",
  "  box-shadow:0 9px 23px rgba(15,39,71,.17);",
  "  font-size:11px;font-weight:650;",
  "}",
  ".tell::after {",
  "  content:\"\";",
  "  display:block;",
  "  width:5px;height:5px;border-radius:50%;",
  "  background:var(--talera-warm);",
  "  margin:3px auto 0;",
  "  opacity:.88;",
  "}",
  ".more { width:22px;letter-spacing:3px;font-size:18px;line-height:1; }",
  "",
  ".debug-panel {",
  "  position:absolute;right:6px;top:6px;z-index:20;display:none;gap:3px;flex-wrap:wrap;width:218px;justify-content:flex-end;",
  "}",
  ".debug-panel.show { display:flex; }",
  ".debug-panel button {",
  "  border:1px solid rgba(15,39,71,.10);",
  "  background:rgba(255,254,252,.96);",
  "  color:var(--talera-deep);",
  "  border-radius:999px;padding:4px 6px;font-size:8px;",
  "}",
  ".debug-panel button.active {",
  "  color:var(--talera-deep);",
  "  border-color:rgba(91,143,185,.35);",
  "  background:rgba(220,234,246,.72);",
  "}",
  "",
  "",
  "",
  ".example-photo {",
  "  position:absolute;",
  "  inset:0;",
  "  width:100%;",
  "  height:100%;",
  "  max-width:none;",
  "  display:block;",
  "  object-fit:cover;",
  "  object-position:center center;",
  "}",
  ".memory-caption {",
  "  position:absolute;",
  "  left:22px;",
  "  right:22px;",
  "  bottom:20px;",
  "  z-index:3;",
  "  color:#fff;",
  "  text-shadow:0 1px 10px rgba(15,39,71,.34);",
  "}",
  ".memory-caption .date {",
  "  font-size:14px;",
  "  font-weight:700;",
  "  letter-spacing:.01em;",
  "  margin-bottom:4px;",
  "}",
  ".memory-caption .story {",
  "  font-size:13px;",
  "  line-height:1.38;",
  "  max-width:31ch;",
  "}",
  "",
  "",
  ".zoom-hint {",
  "  position:absolute;",
  "  z-index:8;",
  "  left:50%;",
  "  bottom:12px;",
  "  transform:translate(-50%, 7px);",
  "  padding:7px 12px;",
  "  border-radius:999px;",
  "  background:rgba(255,254,252,.95);",
  "  border:1px solid rgba(91,143,185,.24);",
  "  color:var(--talera-deep);",
  "  box-shadow:0 6px 18px rgba(15,39,71,.08);",
  "  font-size:12px;",
  "  font-weight:650;",
  "  letter-spacing:.01em;",
  "  white-space:nowrap;",
  "  opacity:0;",
  "  pointer-events:none;",
  "  transition:opacity .22s ease, transform .22s ease;",
  "}",
  ".zoom-hint.show {",
  "  opacity:1;",
  "  transform:translate(-50%, 0);",
  "}",
  ".zoom-hint.hide {",
  "  opacity:0;",
  "  transform:translate(-50%, 5px);",
  "}",
  "",
  "",
  "/* v20 StoryFlow: the active memory is always readable and never empty. */",
  ".memory-space::before {",
  "  background:linear-gradient(",
  "    180deg,",
  "    rgba(247,244,239,0) 44%,",
  "    rgba(247,244,239,.16) 58%,",
  "    rgba(247,244,239,.84) 77%,",
  "    rgba(247,244,239,.98) 100%",
  "  );",
  "  z-index:2;",
  "}",
  ".example-photo {",
  "  transition:opacity .24s ease, filter .32s ease, transform .42s ease, object-position .42s ease;",
  "}",
  ".example-photo.story-switching {",
  "  opacity:.74;",
  "}",
  ".memory-caption {",
  "  left:0;",
  "  right:0;",
  "  bottom:0;",
  "  z-index:3;",
  "  padding:64px 22px 20px;",
  "  color:var(--talera-deep);",
  "  text-shadow:none;",
  "  background:linear-gradient(",
  "    180deg,",
  "    rgba(247,244,239,0) 0%,",
  "    rgba(247,244,239,.62) 42%,",
  "    rgba(247,244,239,.94) 72%,",
  "    rgba(247,244,239,.99) 100%",
  "  );",
  "  opacity:1;",
  "  transform:translateY(0);",
  "  transition:opacity .20s ease, transform .24s ease;",
  "  pointer-events:auto;",
  "  max-height:52%;",
  "  overflow-y:auto;",
  "  -webkit-overflow-scrolling:touch;",
  "}",
  ".memory-caption.story-switching {",
  "  opacity:.18;",
  "  transform:translateY(5px);",
  "}",
  ".memory-caption .date {",
  "  color:rgba(15,39,71,.72);",
  "  font-size:13px;",
  "  font-weight:700;",
  "  letter-spacing:.01em;",
];
