export const chunk9 = [
  "  drawScale(level,startMs,endMs,w,axisY);",
  "",
  "  if(Math.abs(centerMs-LIFE_END)<60000) {",
  "    focusText.textContent=\"vandaag\";",
  "  } else if(level===5) {",
  "    focusText.textContent=new Date(centerMs).toLocaleTimeString(\"nl-NL\",{hour:\"2-digit\",minute:\"2-digit\"});",
  "  } else {",
  "    focusText.textContent=new Date(centerMs).toLocaleDateString(\"nl-NL\",{day:\"numeric\",month:\"short\",year:\"numeric\"});",
  "  }",
  "",
  "  if (userIsMoving) renderJourneyPreview();",
  "  updateNearestStory();",
  "",
  "  [...debugPanel.children].forEach((b,i)=>b.classList.toggle(\"active\",i===level));",
  "}",
  "",
  "if(new URLSearchParams(location.search).get(\"debug\")===\"1\") {",
  "  debugPanel.classList.add(\"show\");",
  "  LEVELS.forEach((l,i)=>{",
  "    const b=document.createElement(\"button\");",
  "    b.textContent=`${i+1} · ${l.name}`;",
  "    b.addEventListener(\"click\",e=>{e.stopPropagation();animateZoomTo(i,360);});",
  "    debugPanel.appendChild(b);",
  "  });",
  "}",
  "",
  "const pointers=new Map();",
  "let dragStartX=0,dragStartCenter=0,pinchStartDist=0,pinchStartZoom=0,pinchStartCenter=0,pinchStartMidX=0;",
  "let dragLastX=0,dragLastT=0,searchVelocity=0;",
  "",
  "/* ---------------------------------------------------------",
  "   ORGANIC SEARCH SCALE.",
  "   Fast horizontal movement keeps / returns the timeline to life overview.",
  "   Calm precise movement progressively moves closer to years, months, weeks",
  "   and days. The center date never jumps: horizontal travel is applied in",
  "   small increments using the scale that was visible for that increment.",
  "   --------------------------------------------------------- */",
  "function autoZoomTarget(speed) {",
  "  const v=Math.max(0,speed);",
  "  return clamp(4.8-Math.log1p(v*18)*1.75,0,4.8);",
  "}",
  "",
  "function updateAutoZoom(speed,dt) {",
  "  const target=autoZoomTarget(speed);",
  "  const tau=target<zoomPos?95:205;",
  "  const alpha=1-Math.exp(-Math.max(8,dt)/tau);",
  "  zoomPos=clamp(lerp(zoomPos,target,alpha),0,5);",
  "}",
  "",
  "surface.addEventListener(\"pointerdown\",e=>{",
  "  if(e.target.closest(\"button\")) return;",
  "  userIsMoving = true;",
  "  surface.setPointerCapture(e.pointerId);",
  "  pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});",
  "  if(pointers.size===1) {",
  "    dragStartX=e.clientX;dragStartCenter=centerMs;",
  "    dragLastX=e.clientX;dragLastT=performance.now();searchVelocity=0;",
  "  } else if(pointers.size===2) {",
  "    markZoomDiscovered();",
  "    const p=[...pointers.values()];",
  "    pinchStartDist=Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y);",
  "    pinchStartZoom=zoomPos;pinchStartCenter=centerMs;pinchStartMidX=(p[0].x+p[1].x)/2;",
  "  }",
  "});",
  "",
  "surface.addEventListener(\"pointermove\",e=>{",
  "  if(!pointers.has(e.pointerId)) return;",
  "  pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});",
  "  const r=surface.getBoundingClientRect();",
  "",
  "  if(pointers.size===1) {",
  "    const now=performance.now();",
  "    const dx=e.clientX-dragLastX;",
  "    const dt=clamp(now-dragLastT,8,48);",
  "    const instantVelocity=Math.abs(dx)/dt;",
  "    const velocityAlpha=1-Math.exp(-dt/62);",
  "    searchVelocity=searchVelocity===0?instantVelocity:lerp(searchVelocity,instantVelocity,velocityAlpha);",
  "",
  "    const movementSpan=spanForZoom(zoomPos);",
  "    centerMs-=(dx/r.width)*movementSpan*MS_DAY;",
  "    updateAutoZoom(searchVelocity,dt);",
  "",
  "    dragLastX=e.clientX;dragLastT=now;",
  "    keepCenterValid();draw();",
  "  } else if(pointers.size===2) {",
  "    const p=[...pointers.values()];",
  "    const dist=Math.max(20,Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y));",
  "    const mid=(p[0].x+p[1].x)/2;",
  "    zoomPos=clamp(pinchStartZoom+Math.log(dist/pinchStartDist)*1.8,0,5);",
  "",
  "    const oldSpan=spanForZoom(pinchStartZoom), newSpan=spanForZoom(zoomPos);",
  "    const oldRel=(pinchStartMidX-r.left)/r.width-.5;",
  "    const anchor=pinchStartCenter+oldRel*oldSpan*MS_DAY;",
  "    const newRel=(mid-r.left)/r.width-.5;",
  "    centerMs=anchor-newRel*newSpan*MS_DAY;",
  "",
  "    keepCenterValid();draw();",
  "  }",
  "});",
  "",
  "function pointerEnd(e) {",
  "  if(pointers.has(e.pointerId)) pointers.delete(e.pointerId);",
  "  if(pointers.size===0) {",
  "    userIsMoving = false;",
  "    updateNearestStory({force:true});",
  "    scheduleSnap();",
  "    searchVelocity=0;",
  "  } else if(pointers.size===1) {",
  "    const p=[...pointers.values()][0];",
  "    dragStartX=p.x;dragStartCenter=centerMs;",
  "    dragLastX=p.x;dragLastT=performance.now();searchVelocity=0;",
  "  }",
  "}",
  "surface.addEventListener(\"pointerup\",pointerEnd);",
  "surface.addEventListener(\"pointercancel\",pointerEnd);",
  "",
  "surface.addEventListener(\"wheel\",e=>{",
  "  e.preventDefault();",
  "  userIsMoving = true;",
  "  const r=surface.getBoundingClientRect();",
  "  if(Math.abs(e.deltaX)>Math.abs(e.deltaY)*.75) {",
  "    centerMs+=(e.deltaX/r.width)*spanForZoom(zoomPos)*MS_DAY;",
  "    keepCenterValid();draw();",
  "  } else {",
  "    zoomPos=clamp(zoomPos-e.deltaY*.004,0,5);",
  "    keepCenterValid();draw();scheduleSnap();",
  "  }",
  "  clearTimeout(candidateTimer);",
  "  candidateTimer=setTimeout(()=>{",
  "    userIsMoving=false;",
  "    updateNearestStory({force:true});",
  "  },120);",
  "},{passive:false});",
  "",
  "function scheduleSnap() {",
  "  clearTimeout(snapTimer);",
  "  snapTimer=setTimeout(()=>animateZoomTo(Math.round(zoomPos),280),170);",
  "}",
  "function animateZoomTo(target,duration) {",
  "  cancelAnimationFrame(raf);",
  "  const from=zoomPos,start=performance.now();",
  "  function frame(now) {",
  "    const t=clamp((now-start)/duration,0,1);",
  "    zoomPos=lerp(from,target,ease(t));",
  "    keepCenterValid();draw();",
  "    if(t<1) raf=requestAnimationFrame(frame);",
  "  }",
  "  raf=requestAnimationFrame(frame);",
  "}",
  "",
  "// Canvas follows the ACTUAL size of the timeline container.",
  "const timelineResizeObserver = new ResizeObserver(() => resize());",
  "timelineResizeObserver.observe(surface);",
  "",
  "window.addEventListener(\"resize\", resize, {passive:true});",
  "window.addEventListener(\"orientationchange\", () => {",
  "  requestAnimationFrame(resize);",
  "  setTimeout(resize, 120);",
  "}, {passive:true});",
  "",
  "if (window.visualViewport) {",
  "  window.visualViewport.addEventListener(\"resize\", resize, {passive:true});",
  "  window.visualViewport.addEventListener(\"scroll\", resize, {passive:true});",
  "}",
  "",
  "window.addEventListener(\"pageshow\", () => {",
  "  requestAnimationFrame(resize);",
  "}, {passive:true});",
  "",
  "document.addEventListener(\"visibilitychange\", () => {",
  "  if (!document.hidden) {",
  "    requestAnimationFrame(resize);",
  "    setTimeout(resize, 80);",
  "  }",
  "}, {passive:true});",
  "",
  "if (memoryStoryScroll) {",
  "  memoryStoryScroll.addEventListener(\"scroll\", () => {",
  "    memoryStoryScroll.classList.toggle(\"is-reading\", memoryStoryScroll.scrollTop > 56);",
  "  }, {passive:true});",
  "}",
  "",
  "// Small public bridge for the presentation layer: photo-book swipes move exactly",
  "// one memory at a time, while the timeline itself keeps its original V16 controls.",
  "window.__taleraPhotoBook = {",
  "  state() {",
  "    const index=Math.max(0,MEMORIES.findIndex(m=>m.id===activeMemoryId));",
  "    const current=MEMORIES[index];",
  "    const previous=MEMORIES[index-1]||null;",
  "    const next=MEMORIES[index+1]||null;",
  "    return {index,current,previous,next};",
  "  },",
  "  step(direction) {",
  "    const index=Math.max(0,MEMORIES.findIndex(m=>m.id===activeMemoryId));",
  "    const targetIndex=clamp(index+direction,0,MEMORIES.length-1);",
  "    const target=MEMORIES[targetIndex];",
  "    if(!target || target.id===activeMemoryId) return false;",
  "    userIsMoving=false;",
  "    centerMs=target.ms;",
  "    keepCenterValid();",
  "    writeMemory(target);",
  "    draw();",
  "    return true;",
  "  }",
  "};",
  "",
  "writeMemory(nearestMemory(centerMs));",
  "resize();",
  "})();",
  "</script>",
  "",
  "",
  "</body>",
  "</html>",
];
