export const chunk2 = [
  "  margin-bottom:7px;",
  "}",
  ".memory-caption .story {",
  "  color:var(--talera-deep);",
  "  font-size:16px;",
  "  line-height:1.45;",
  "  font-weight:520;",
  "  max-width:34ch;",
  "}",
  "",
  "",
  "/* v21 LIFEBOOK — horizontal through life, vertical into one memory */",
  ".memory-space { position:relative; overflow:hidden; background:var(--talera-neutral); }",
  ".example-photo {",
  "  position:absolute; inset:0; width:100%; height:100%; object-fit:cover; object-position:center center;",
  "  z-index:1; opacity:1; transform:scale(1.001);",
  "  transition:opacity .34s ease, transform .48s ease;",
  "  will-change:opacity,transform;",
  "}",
  ".example-photo.story-switching { opacity:.12; transform:scale(1.018); }",
  ".memory-space::before {",
  "  content:\"\"; position:absolute; inset:0; z-index:2; pointer-events:none;",
  "  background:linear-gradient(180deg,rgba(15,39,71,0) 35%,rgba(15,39,71,.03) 54%,rgba(15,39,71,.30) 76%,rgba(15,39,71,.56) 100%);",
  "}",
  ".memory-story-scroll {",
  "  position:absolute; inset:0; z-index:3; overflow-y:auto; overflow-x:hidden;",
  "  -webkit-overflow-scrolling:touch; overscroll-behavior-y:contain; scrollbar-width:none; touch-action:pan-y;",
  "}",
  ".memory-story-scroll::-webkit-scrollbar { display:none; }",
  ".memory-photo-air { height:62%; min-height:170px; pointer-events:none; }",
  ".memory-sheet {",
  "  position:relative; min-height:68%; box-sizing:border-box; padding:62px 22px 92px;",
  "  background:linear-gradient(180deg,rgba(247,244,239,0) 0px,rgba(247,244,239,.70) 38px,rgba(247,244,239,.96) 92px,rgba(247,244,239,1) 150px);",
  "  color:var(--talera-deep); opacity:1; transform:translateY(0);",
  "  transition:opacity .22s ease, transform .28s ease;",
  "}",
  ".memory-sheet.story-switching { opacity:.12; transform:translateY(8px); }",
  ".memory-sheet .date {",
  "  font-size:13px; line-height:1.2; font-weight:720; color:rgba(15,39,71,.68);",
  "  margin:0 0 8px; letter-spacing:.01em;",
  "}",
  ".memory-sheet .story {",
  "  font-size:17px; line-height:1.43; font-weight:620; color:var(--talera-deep);",
  "  max-width:35ch; white-space:pre-line;",
  "}",
  ".memory-sheet .story-more {",
  "  margin-top:18px; padding-top:16px; border-top:1px solid rgba(15,39,71,.10);",
  "  font-size:16px; line-height:1.58; font-weight:430; color:var(--talera-text);",
  "  max-width:39ch; white-space:pre-line;",
  "}",
  ".memory-sheet::before {",
  "  content:\"↑\"; position:absolute; top:30px; left:22px; font-size:14px; color:rgba(15,39,71,.48);",
  "}",
  "@media (max-width:380px) {",
  "  .memory-photo-air { height:59%; }",
  "  .memory-sheet { padding-left:18px; padding-right:18px; }",
  "}",
  "",
  "",
  "/* =========================================================",
  "   v22 PHOTOBOOK",
  "   One memory = one recognisable photograph + story.",
  "   Horizontal = through life. Vertical = into the story.",
  "   ========================================================= */",
  "",
  ".memory-space {",
  "  --story-neutral: 247,244,239;",
  "  background:rgb(var(--story-neutral));",
  "}",
  "",
  "/* Remove the old dark photo overlay; colour now comes from the blurred photograph itself. */",
  ".memory-space::before { display:none !important; }",
  "",
  ".photo-stage {",
  "  position:absolute;",
  "  inset:0;",
  "  z-index:1;",
  "  overflow:hidden;",
  "  background:#dfe6eb;",
  "}",
  ".photo-layer {",
  "  position:absolute;",
  "  inset:0;",
  "  opacity:0;",
  "  transform:translate3d(5%,0,0) scale(1.012);",
  "  transition:opacity .28s ease, transform .34s cubic-bezier(.22,.72,.25,1);",
  "  will-change:opacity,transform;",
  "}",
  ".photo-layer.is-front {",
  "  opacity:1;",
  "  transform:translate3d(0,0,0) scale(1);",
  "}",
  ".photo-backdrop {",
  "  position:absolute;",
  "  inset:-24px;",
  "  width:calc(100% + 48px);",
  "  height:calc(100% + 48px);",
  "  object-fit:cover;",
  "  filter:blur(20px) saturate(.82) brightness(.88);",
  "  opacity:.80;",
  "  transform:scale(1.07);",
  "}",
  ".example-photo {",
  "  position:absolute;",
  "  inset:0;",
  "  z-index:2;",
  "  width:100%;",
  "  height:100%;",
  "  max-width:none;",
  "  display:block;",
  "  object-fit:contain !important;",
  "  object-position:center center !important;",
  "  filter:none !important;",
  "  transform:none !important;",
  "  opacity:1 !important;",
  "  background:transparent;",
  "}",
  "",
  "/* The lower part of the actual photograph becomes a quiet colour field.",
  "   No hard line, no white card edge. */",
  ".memory-space::after {",
  "  content:\"\";",
  "  position:absolute;",
  "  left:0; right:0; bottom:0;",
  "  height:46%;",
  "  z-index:2;",
  "  pointer-events:none;",
  "  -webkit-backdrop-filter:blur(12px) saturate(.90);",
  "  backdrop-filter:blur(12px) saturate(.90);",
  "  background:linear-gradient(",
  "    180deg,",
  "    rgba(var(--story-neutral),0) 0%,",
  "    rgba(var(--story-neutral),.06) 30%,",
  "    rgba(var(--story-neutral),.24) 58%,",
  "    rgba(var(--story-neutral),.74) 100%",
  "  );",
  "}",
  "",
  "/* Photo first. Only the beginning of the story is visible at rest. */",
  ".memory-story-scroll {",
  "  z-index:4;",
  "}",
  ".memory-photo-air {",
  "  height:70%;",
  "  min-height:210px;",
  "}",
  ".memory-sheet {",
  "  min-height:76%;",
  "  padding:56px 22px 96px;",
  "  background:linear-gradient(",
  "    180deg,",
  "    rgba(var(--story-neutral),0) 0px,",
  "    rgba(var(--story-neutral),.22) 28px,",
  "    rgba(var(--story-neutral),.68) 74px,",
  "    rgba(var(--story-neutral),.96) 132px,",
  "    rgb(var(--story-neutral)) 182px",
  "  );",
  "}",
  ".memory-sheet::before {",
  "  content:\"↑\";",
  "  top:27px;",
  "  color:rgba(15,39,71,.42);",
  "}",
  ".memory-sheet .date {",
  "  color:rgba(15,39,71,.68);",
  "  font-size:13px;",
  "  margin-bottom:7px;",
  "}",
  ".memory-sheet .story {",
  "  font-size:16px;",
  "  line-height:1.42;",
  "  font-weight:650;",
  "  max-width:36ch;",
  "}",
  ".memory-sheet .story-more {",
  "  margin-top:18px;",
  "  padding-top:18px;",
  "  font-size:16px;",
  "  line-height:1.62;",
  "}",
  "",
  "/* When the reader pulls the story upward, the sheet itself becomes the clean reading surface. */",
  ".memory-story-scroll.is-reading .memory-sheet {",
  "  background:linear-gradient(",
  "    180deg,",
  "    rgba(var(--story-neutral),.88) 0px,",
  "    rgb(var(--story-neutral)) 100px",
  "  );",
  "}",
  "",
  "/* Slightly more compact reserved navigation; the won height goes to the photo/story. */",
  "nav {",
  "  height:60px !important;",
  "  min-height:60px !important;",
  "  max-height:60px !important;",
  "  padding-top:2px;",
  "  padding-bottom:2px;",
  "}",
  ".tell {",
  "  width:50px !important;",
  "  height:50px !important;",
  "}",
  ".nav-item {",
  "  min-height:38px !important;",
  "  gap:2px;",
  "  font-size:9px;",
  "}",
  "",
  "/* Short phones still keep the photograph dominant. */",
  "@media (max-height:700px) {",
  "  .memory-photo-air { height:66%; min-height:180px; }",
  "  .memory-sheet { padding-top:50px; }",
  "}",
  "",
  "</style>",
  "</head>",
  "<body>",
  "<div class=\"app\">",
  "  <main>",
  "    <section class=\"timeline\" id=\"surface\" aria-label=\"TALERA levenslijn\">",
  "      <canvas id=\"timelineCanvas\"></canvas>",
  "      <div class=\"center-needle\"></div>",
  "      <div class=\"focus\" id=\"focusText\">vandaag</div>",
  "      <div class=\"zoom-hint\" id=\"zoomHint\">Knijp om in te zoomen</div>",
  "      <div class=\"debug-panel\" id=\"debugPanel\"></div>",
  "    </section>",
  "",
  "    <section class=\"memory-space\" aria-label=\"Ruimte voor actieve herinnering\">",
  "      <div class=\"photo-stage\" id=\"photoStage\" aria-hidden=\"true\">",
  "        <div class=\"photo-layer is-front\" id=\"photoLayerA\">",
  "          <img class=\"photo-backdrop\" id=\"memoryBackdropA\" src=\"https://images.unsplash.com/photo-1772033085549-032412902a23?auto=format&fit=max&fm=jpg&q=76&w=1400\" alt=\"\">",
  "          <img class=\"example-photo\" id=\"memoryPhotoA\" src=\"https://images.unsplash.com/photo-1772033085549-032412902a23?auto=format&fit=max&fm=jpg&q=76&w=1400\" alt=\"Foto bij actieve herinnering\">",
  "        </div>",
  "        <div class=\"photo-layer\" id=\"photoLayerB\">",
  "          <img class=\"photo-backdrop\" id=\"memoryBackdropB\" src=\"https://images.unsplash.com/photo-1772033085549-032412902a23?auto=format&fit=max&fm=jpg&q=76&w=1400\" alt=\"\">",
  "          <img class=\"example-photo\" id=\"memoryPhotoB\" src=\"https://images.unsplash.com/photo-1772033085549-032412902a23?auto=format&fit=max&fm=jpg&q=76&w=1400\" alt=\"\">",
  "        </div>",
  "      </div>",
  "      <div class=\"memory-story-scroll\" id=\"memoryStoryScroll\">",
  "        <div class=\"memory-photo-air\" aria-hidden=\"true\"></div>",
  "        <article class=\"memory-sheet is-visible\" id=\"memoryCaption\">",
];
