export const chunk7 = [
  "const EVENT_OFFSETS = MEMORIES.map(m => (m.ms - LIFE_START) / MS_DAY);",
  "",
  "const LEVELS = [",
  "  {name:\"15 jaar\", spanDays:DAYS_YEAR*15},",
  "  {name:\"2 jaar\", spanDays:DAYS_YEAR*2},",
  "  {name:\"3 maanden\", spanDays:91.31},",
  "  {name:\"2 weken\", spanDays:14},",
  "  {name:\"1 dag\", spanDays:1},",
  "  {name:\"24 uur\", spanDays:1}",
  "];",
  "",
  "const canvas = document.getElementById(\"timelineCanvas\");",
  "const ctx = canvas.getContext(\"2d\");",
  "const surface = document.getElementById(\"surface\");",
  "const focusText = document.getElementById(\"focusText\");",
  "const debugPanel = document.getElementById(\"debugPanel\");",
  "",
  "const photoLayerA = document.getElementById(\"photoLayerA\");",
  "const photoLayerB = document.getElementById(\"photoLayerB\");",
  "const memoryPhotoA = document.getElementById(\"memoryPhotoA\");",
  "const memoryPhotoB = document.getElementById(\"memoryPhotoB\");",
  "const memoryBackdropA = document.getElementById(\"memoryBackdropA\");",
  "const memoryBackdropB = document.getElementById(\"memoryBackdropB\");",
  "const memoryCaption = document.getElementById(\"memoryCaption\");",
  "const memoryDate = document.getElementById(\"memoryDate\");",
  "const memoryStory = document.getElementById(\"memoryStory\");",
  "const memoryStoryMore = document.getElementById(\"memoryStoryMore\");",
  "const memoryStoryScroll = document.getElementById(\"memoryStoryScroll\");",
  "",
  "let activeMemoryId = 50;        // HTML fallback is memory 50.",
  "let pendingMemoryId = null;",
  "let storySwitchTimer = 0;",
  "let candidateTimer = 0;",
  "let userIsMoving = false;",
  "",
  "let layerAImage = \"\";",
  "let layerBImage = \"\";",
  "let lastJourneyLeft = null;",
  "let lastJourneyRight = null;",
  "",
  "function setPhotoLayer(layer, foreground, backdrop, src, opacity, xPercent=0) {",
  "  if (!src) return;",
  "  if (foreground.src !== src) foreground.src = src;",
  "  if (backdrop.src !== src) backdrop.src = src;",
  "  layer.style.opacity = String(opacity);",
  "  layer.style.transform = `translate3d(${xPercent}%,0,0) scale(${1 + Math.abs(xPercent)*.0012})`;",
  "}",
  "",
  "function preloadAround(memory) {",
  "  const index = MEMORIES.findIndex(m => m.id === memory.id);",
  "  for (const offset of [-2,-1,0,1,2]) {",
  "    const item = MEMORIES[index + offset];",
  "    if (!item) continue;",
  "    const img = new Image();",
  "    img.decoding = \"async\";",
  "    img.src = item.image;",
  "  }",
  "}",
  "",
  "function surroundingMemories(ms) {",
  "  if (ms <= MEMORIES[0].ms) return {left:MEMORIES[0], right:MEMORIES[0], progress:0};",
  "  const last = MEMORIES[MEMORIES.length-1];",
  "  if (ms >= last.ms) return {left:last, right:last, progress:0};",
  "",
  "  let hi = 1;",
  "  while (hi < MEMORIES.length && MEMORIES[hi].ms < ms) hi++;",
  "  const left = MEMORIES[hi-1];",
  "  const right = MEMORIES[hi];",
  "  const progress = (ms-left.ms) / Math.max(1, right.ms-left.ms);",
  "  return {left,right,progress:clamp(progress,0,1)};",
  "}",
  "",
  "function renderJourneyPreview() {",
  "  if (!userIsMoving) return;",
  "",
  "  const {left,right,progress} = surroundingMemories(centerMs);",
  "  if (!left || !right) return;",
  "",
  "  const p = progress*progress*(3-2*progress); // smoothstep",
  "",
  "  setPhotoLayer(photoLayerA, memoryPhotoA, memoryBackdropA, left.image, 1-p, -7*p);",
  "  setPhotoLayer(photoLayerB, memoryPhotoB, memoryBackdropB, right.image, p, 7*(1-p));",
  "",
  "  lastJourneyLeft = left.id;",
  "  lastJourneyRight = right.id;",
  "}",
  "",
  "function settlePhoto(memory) {",
  "  setPhotoLayer(photoLayerA, memoryPhotoA, memoryBackdropA, memory.image, 1, 0);",
  "  setPhotoLayer(photoLayerB, memoryPhotoB, memoryBackdropB, memory.image, 0, 5);",
  "  preloadAround(memory);",
  "}",
  "",
  "",
  "function nearestMemory(ms) {",
  "  // If several stories share exactly the same timeline moment, keep the",
  "  // memory the user is already on. This prevents a freshly linked story",
  "  // from snapping back to an older story with the same event date.",
  "  if (!MEMORIES.length) return null;",
  "  const active = MEMORIES.find(m => m.id === activeMemoryId);",
  "  let best = active || MEMORIES[0];",
  "  let bestDistance = Math.abs(best.ms - ms);",
  "  for (const memory of MEMORIES) {",
  "    const distance = Math.abs(memory.ms - ms);",
  "    if (distance < bestDistance) {",
  "      best = memory;",
  "      bestDistance = distance;",
  "    }",
  "  }",
  "  return best;",
  "}",
  "",
  "function formatMemoryDate(memory) {",
  "  const d = new Date(memory.ms);",
  "  const sameDayCount = MEMORIES.reduce((n,m) => {",
  "    const md = new Date(m.ms);",
  "    return n + (",
  "      md.getFullYear()===d.getFullYear() &&",
  "      md.getMonth()===d.getMonth() &&",
  "      md.getDate()===d.getDate() ? 1 : 0",
  "    );",
  "  },0);",
  "",
  "  const date = d.toLocaleDateString(\"nl-NL\", {",
  "    day:\"numeric\", month:\"long\", year:\"numeric\"",
  "  });",
  "",
  "  if (sameDayCount > 1) {",
  "    const time = d.toLocaleTimeString(\"nl-NL\", {",
  "      hour:\"2-digit\", minute:\"2-digit\"",
  "    });",
  "    return `${date} · ${time}`;",
  "  }",
  "  return date;",
  "}",
  "",
  "function writeMemory(memory) {",
  "  activeMemoryId = memory.id;",
  "  pendingMemoryId = null;",
  "",
  "  if (memoryDate) memoryDate.textContent = formatMemoryDate(memory);",
  "  if (memoryStory) memoryStory.textContent = memory.story;",
  "",
  "  if (memoryStoryMore) {",
  "    const remainder = memory.fullStory.startsWith(memory.story)",
  "      ? memory.fullStory.slice(memory.story.length).trim()",
  "      : memory.fullStory;",
  "    memoryStoryMore.textContent = remainder;",
  "  }",
  "",
  "  settlePhoto(memory);",
  "",
  "  // Every new memory starts in photo-first position.",
  "  if (memoryStoryScroll) {",
  "    memoryStoryScroll.scrollTop = 0;",
  "    memoryStoryScroll.classList.remove(\"is-reading\");",
  "  }",
  "}",
  "",
  "function switchToMemory(memory, immediate=false) {",
  "  if (!memory || memory.id === activeMemoryId) return;",
  "",
  "  clearTimeout(storySwitchTimer);",
  "",
  "  if (immediate || !memoryCaption) {",
  "    writeMemory(memory);",
  "    return;",
  "  }",
  "",
  "  pendingMemoryId = memory.id;",
  "  memoryCaption.classList.add(\"story-switching\");",
  "  ",
  "",
  "  storySwitchTimer = setTimeout(() => {",
  "    // If a newer candidate arrived during the fade, use that instead.",
  "    const chosen = pendingMemoryId",
  "      ? MEMORIES.find(m => m.id === pendingMemoryId) || memory",
  "      : memory;",
  "",
  "    writeMemory(chosen);",
  "",
  "    requestAnimationFrame(() => {",
  "      memoryCaption.classList.remove(\"story-switching\");",
  "      ",
  "    });",
  "  }, 165);",
  "}",
  "",
  "function updateNearestStory({force=false} = {}) {",
  "  const nearest = nearestMemory(centerMs);",
  "  if (!nearest || nearest.id === activeMemoryId) return;",
  "",
  "  if (userIsMoving && !force) {",
  "    pendingMemoryId = nearest.id;",
  "    return;",
  "  }",
  "",
  "  switchToMemory(nearest, false);",
  "}",
  "",
  "",
  "const zoomHint = document.getElementById(\"zoomHint\");",
  "const ZOOM_HINT_KEY = \"talera_zoom_discovered_v1\";",
  "let zoomHintTimer = null;",
  "",
  "function zoomAlreadyDiscovered() {",
  "  try { return localStorage.getItem(ZOOM_HINT_KEY) === \"1\"; }",
  "  catch(e) { return false; }",
  "}",
  "",
  "function showZoomHint() {",
  "  if (!zoomHint || zoomAlreadyDiscovered()) return;",
  "  zoomHint.classList.remove(\"hide\");",
  "  zoomHint.classList.add(\"show\");",
  "  clearTimeout(zoomHintTimer);",
  "  zoomHintTimer = setTimeout(() => {",
  "    zoomHint.classList.remove(\"show\");",
  "    zoomHint.classList.add(\"hide\");",
  "  }, 4200);",
  "}",
  "",
  "function markZoomDiscovered() {",
  "  try { localStorage.setItem(ZOOM_HINT_KEY, \"1\"); } catch(e) {}",
  "  clearTimeout(zoomHintTimer);",
  "  if (zoomHint) {",
  "    zoomHint.classList.remove(\"show\");",
  "    zoomHint.classList.add(\"hide\");",
  "  }",
  "}",
  "",
  "setTimeout(showZoomHint, 650);",
  "",
  "",
  "const dayCounts = new Uint16Array(TOTAL_DAYS);",
  "for(const o of EVENT_OFFSETS) {",
  "  const day=Math.floor(o);",
  "  if(day>=0 && day<TOTAL_DAYS) dayCounts[day]++;",
  "}",
  "",
  "let zoomPos=0;",
  "let centerMs=LIFE_END;",
  "let raf=0;",
  "let snapTimer=0;",
  "",
  "const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));",
  "const lerp=(a,b,t)=>a+(b-a)*t;",
  "const ease=t=>1-Math.pow(1-t,3);",
  "",
  "function ageAt(ms) { return (ms-LIFE_START)/MS_DAY/DAYS_YEAR; }",
  "",
  "function spanForZoom(z) {",
  "  z=clamp(z,0,5);",
  "  if(z>=4) return 1;",
  "  const i=Math.floor(z), t=z-i;",
  "  return Math.exp(lerp(Math.log(LEVELS[i].spanDays),Math.log(LEVELS[i+1].spanDays),t));",
  "}",
  "",
  "function activeLevel() { return clamp(Math.round(zoomPos),0,5); }",
  "",
  "function bounds() {",
  "  const span=spanForZoom(zoomPos);",
  "  const half=span*MS_DAY/2;",
  "  return [centerMs-half,centerMs+half,span];",
  "}",
  "",
  "function keepCenterValid() {",
  "  const span=spanForZoom(zoomPos);",
];
