export const chunk9 = [
  "  drawScale(level,startMs,endMs,w,axisY);",
  "",
  "  if(Math.abs(centerMs-LIFE_END)<60000) {",
  "    focusText.textContent=\"vandaag\";",
  "  } else if(level===5) {",
  "    focusText.textContent=new Date(centerMs).toLocaleTimeString(\"nl-NL\",{hour:\"2-digit\",minute:\"2-digit\"});",
  "  } else {",
  "    focusText.textContent=new Date(centerMs).toLocaleDateString(\"nl-NL\",{day:\"numeric\",month:\"short\",year:\"numeric\"});",
  "  }",
  "",
  "  if (userIsMoving) renderJourneyPreview();",
  "  updateNearestStory();",
  "",
  "  [...debugPanel.children].forEach((b,i)=>b.classList.toggle(\"active\",i===level));",
  "}",
  "",
  "if(new URLSearchParams(location.search).get(\"debug\")===\"1\") {",
  "  debugPanel.classList.add(\"show\");",
  "  LEVELS.forEach((l,i)=>{",
  "    const b=document.createElement(\"button\");",
  "    b.textContent=`${i+1} · ${l.name}`;",
  "    b.addEventListener(\"click\",e=>{e.stopPropagation();animateZoomTo(i,360,true);});",
  "    debugPanel.appendChild(b);",
  "  });",
  "}",
  "",
  "const pointers=new Map();",
  "let dragStartX=0,dragStartCenter=0,pinchStartDist=0,pinchStartZoom=0,pinchStartCenter=0,pinchStartMidX=0;",
  "",
  "/* ---------------------------------------------------------",
  "   STABLE VISUAL SEARCH GEARS.",
  "   The proven center-date navigation keeps using zoomPos unchanged.",
  "   visualZoomPos only controls what the large timeline draws. Deep",
  "   visual detail is now an inspection gear, not a scrolling gear: calm",
  "   browsing stays one level coarser until movement is almost stationary.",
  "   --------------------------------------------------------- */",
  "let visualZoomPos=zoomPos;",
  "let visualScaleRaf=0;",
  "let visualScaleTransitioning=false;",
  "let visualIntentLevel=0;",
  "let visualIntentSince=performance.now();",
  "let visualGearHoldUntil=0;",
  "let scaleLastX=0,scaleLastT=0,searchVelocity=0;",
  "let gestureUsedPinch=false;",
  "",
  "// Automatic detail stops at the 3-month view. Week/day remain explicit pinch territory.",
  "const VISUAL_AUTO_MAX_ZOOM=2;",
  "const VISUAL_GEAR_HOLD_MS=1200;",
  "const VISUAL_ZOOM_IN_DWELL_MS=[0,750,1500];",
  "const VISUAL_ZOOM_OUT_DWELL_MS=170;",
  "",
  "function visualStageForZoom(z) {",
  "  return clamp(Math.round(z),0,2);",
  "}",
  "",
  "function visualTargetForLevel(level) {",
  "  return clamp(level,0,VISUAL_AUTO_MAX_ZOOM);",
  "}",
  "",
  "activeLevel=function() {",
  "  return clamp(Math.round(visualZoomPos),0,5);",
  "};",
  "",
  "bounds=function() {",
  "  const span=spanForZoom(visualZoomPos);",
  "  const half=span*MS_DAY/2;",
  "  return [centerMs-half,centerMs+half,span];",
  "};",
  "",
  "function visualLevelForSpeed(speed) {",
  "  const v=Math.max(0,speed);",
  "  if(v>=.60) return 0;",
  "  // Normal calm browsing deliberately stays at the 2-year/month scale.",
  "  if(v>=.025) return 1;",
  "  // 3-month detail only becomes eligible when the finger is almost still.",
  "  return 2;",
  "}",
  "",
  "function resetVisualIntent(now=performance.now()) {",
  "  visualIntentLevel=visualStageForZoom(visualZoomPos);",
  "  visualIntentSince=now;",
  "}",
  "",
  "function cancelVisualScaleAnimation() {",
  "  cancelAnimationFrame(visualScaleRaf);",
  "  visualScaleRaf=0;",
  "  visualScaleTransitioning=false;",
  "}",
  "",
  "function animateVisualScaleTo(target,duration) {",
  "  cancelAnimationFrame(visualScaleRaf);",
  "  const from=visualZoomPos;",
  "  const start=performance.now();",
  "  visualScaleTransitioning=true;",
  "",
  "  function frame(now) {",
  "    const t=clamp((now-start)/duration,0,1);",
  "    visualZoomPos=lerp(from,target,ease(t));",
  "    draw();",
  "    if(t<1) {",
  "      visualScaleRaf=requestAnimationFrame(frame);",
  "    } else {",
  "      visualZoomPos=target;",
  "      visualScaleTransitioning=false;",
  "      const settledAt=performance.now();",
  "      visualIntentLevel=visualStageForZoom(target);",
  "      visualIntentSince=settledAt;",
  "      visualGearHoldUntil=settledAt+VISUAL_GEAR_HOLD_MS;",
  "      draw();",
  "    }",
  "  }",
  "  visualScaleRaf=requestAnimationFrame(frame);",
  "}",
  "",
  "function considerVisualScale(speed,now) {",
  "  if(visualScaleTransitioning || pointers.size!==1) return;",
  "",
  "  const current=visualStageForZoom(visualZoomPos);",
  "  const desired=visualLevelForSpeed(speed);",
  "  if(desired===current) {",
  "    visualIntentLevel=current;",
  "    visualIntentSince=now;",
  "    return;",
  "  }",
  "",
  "  const strongOverview=desired===0&&current>0&&speed>=.85;",
  "  const readabilityEscape=current===2&&desired===1&&speed>=.055;",
  "  if(desired!==visualIntentLevel) {",
  "    visualIntentLevel=desired;",
  "    visualIntentSince=(strongOverview||readabilityEscape)?now:Math.max(now,visualGearHoldUntil);",
  "    return;",
  "  }",
  "",
  "  // Keep a chosen scale stable, except when the deepest automatic view",
  "  // starts moving too quickly to read or a strong overview swipe begins.",
  "  if(now<visualGearHoldUntil&&!strongOverview&&!readabilityEscape) return;",
  "",
  "  if(desired<current) {",
  "    const dwell=strongOverview?90:(readabilityEscape?110:VISUAL_ZOOM_OUT_DWELL_MS);",
  "    if(now-visualIntentSince<dwell) return;",
  "    animateVisualScaleTo(visualTargetForLevel(desired),desired===0?260:300);",
  "    return;",
  "  }",
  "",
  "  // Refinement is deliberately conservative. Months are the normal fine",
  "  // navigation aid; 3-month detail is reserved for near-still inspection.",
  "  const next=Math.min(VISUAL_AUTO_MAX_ZOOM,current+1);",
  "  if(now-visualIntentSince<VISUAL_ZOOM_IN_DWELL_MS[next]) return;",
  "  animateVisualScaleTo(visualTargetForLevel(next),next===2?420:360);",
  "}",
  "",
  "surface.addEventListener(\"pointerdown\",e=>{",
  "  if(e.target.closest(\"button\")) return;",
  "  userIsMoving = true;",
  "  surface.setPointerCapture(e.pointerId);",
  "  pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});",
  "  if(pointers.size===1) {",
  "    dragStartX=e.clientX;dragStartCenter=centerMs;",
  "    scaleLastX=e.clientX;scaleLastT=performance.now();searchVelocity=0;",
  "    resetVisualIntent(scaleLastT);",
  "    gestureUsedPinch=false;",
  "  } else if(pointers.size===2) {",
  "    markZoomDiscovered();",
  "    gestureUsedPinch=true;",
  "    cancelVisualScaleAnimation();",
  "    visualZoomPos=zoomPos;",
  "    visualGearHoldUntil=0;",
  "    const p=[...pointers.values()];",
  "    pinchStartDist=Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y);",
  "    pinchStartZoom=zoomPos;pinchStartCenter=centerMs;pinchStartMidX=(p[0].x+p[1].x)/2;",
  "  }",
  "});",
  "",
  "surface.addEventListener(\"pointermove\",e=>{",
  "  if(!pointers.has(e.pointerId)) return;",
  "  pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});",
  "  const r=surface.getBoundingClientRect();",
  "",
  "  if(pointers.size===1) {",
  "    const now=performance.now();",
  "    const segmentDx=e.clientX-scaleLastX;",
  "    const dt=clamp(now-scaleLastT,8,48);",
  "    const instantVelocity=Math.abs(segmentDx)/dt;",
  "    const velocityTau=instantVelocity>searchVelocity?70:380;",
  "    const velocityAlpha=1-Math.exp(-dt/velocityTau);",
  "    searchVelocity=searchVelocity===0",
  "      ? instantVelocity",
  "      : lerp(searchVelocity,instantVelocity,velocityAlpha);",
  "",
  "    // IMPORTANT: this is the proven date/marker mapping. Do not couple",
  "    // visual scaling back into this calculation.",
  "    const dx=e.clientX-dragStartX;",
  "    centerMs=dragStartCenter-(dx/r.width)*spanForZoom(zoomPos)*MS_DAY;",
  "",
  "    scaleLastX=e.clientX;scaleLastT=now;",
  "    considerVisualScale(searchVelocity,now);",
  "",
  "    keepCenterValid();draw();",
  "  } else if(pointers.size===2) {",
  "    const p=[...pointers.values()];",
  "    const dist=Math.max(20,Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y));",
  "    const mid=(p[0].x+p[1].x)/2;",
  "    zoomPos=clamp(pinchStartZoom+Math.log(dist/pinchStartDist)*1.8,0,5);",
  "    visualZoomPos=zoomPos;",
  "",
  "    const oldSpan=spanForZoom(pinchStartZoom), newSpan=spanForZoom(zoomPos);",
  "    const oldRel=(pinchStartMidX-r.left)/r.width-.5;",
  "    const anchor=pinchStartCenter+oldRel*oldSpan*MS_DAY;",
  "    const newRel=(mid-r.left)/r.width-.5;",
  "    centerMs=anchor-newRel*newSpan*MS_DAY;",
  "",
  "    keepCenterValid();draw();",
  "  }",
  "});",
  "",
  "function pointerEnd(e) {",
  "  if(pointers.has(e.pointerId)) pointers.delete(e.pointerId);",
  "  if(pointers.size===0) {",
  "    userIsMoving = false;",
  "    updateNearestStory({force:true});",
  "    scheduleSnap(gestureUsedPinch);",
  "    searchVelocity=0;",
  "  } else if(pointers.size===1) {",
  "    const p=[...pointers.values()][0];",
  "    dragStartX=p.x;dragStartCenter=centerMs;",
  "    scaleLastX=p.x;scaleLastT=performance.now();searchVelocity=0;",
  "    resetVisualIntent(scaleLastT);",
  "  }",
  "}",
  "surface.addEventListener(\"pointerup\",pointerEnd);",
  "surface.addEventListener(\"pointercancel\",pointerEnd);",
  "",
  "surface.addEventListener(\"wheel\",e=>{",
  "  e.preventDefault();",
  "  userIsMoving = true;",
  "  const r=surface.getBoundingClientRect();",
  "  if(Math.abs(e.deltaX)>Math.abs(e.deltaY)*.75) {",
  "    centerMs+=(e.deltaX/r.width)*spanForZoom(zoomPos)*MS_DAY;",
  "    keepCenterValid();draw();",
  "  } else {",
  "    cancelVisualScaleAnimation();",
  "    zoomPos=clamp(zoomPos-e.deltaY*.004,0,5);",
  "    visualZoomPos=zoomPos;",
  "    visualGearHoldUntil=0;",
  "    keepCenterValid();draw();scheduleSnap(true);",
  "  }",
  "  clearTimeout(candidateTimer);",
  "  candidateTimer=setTimeout(()=>{",
  "    userIsMoving=false;",
  "    updateNearestStory({force:true});",
  "  },120);",
  "},{passive:false});",
  "",
  "function scheduleSnap(syncVisual=false) {",
  "  clearTimeout(snapTimer);",
  "  snapTimer=setTimeout(()=>animateZoomTo(Math.round(zoomPos),280,syncVisual),170);",
  "}",
  "function animateZoomTo(target,duration,syncVisual=false) {",
  "  cancelAnimationFrame(raf);",
  "  const from=zoomPos,start=performance.now();",
  "  if(syncVisual) cancelVisualScaleAnimation();",
  "  function frame(now) {",
  "    const t=clamp((now-start)/duration,0,1);",
  "    zoomPos=lerp(from,target,ease(t));",
  "    if(syncVisual) visualZoomPos=zoomPos;",
  "    keepCenterValid();draw();",
  "    if(t<1) raf=requestAnimationFrame(frame);",
  "  }",
  "  raf=requestAnimationFrame(frame);",
  "}",
  "",
  "// Canvas follows the ACTUAL size of the timeline container.",
  "const timelineResizeObserver = new ResizeObserver(() => resize());",
  "timelineResizeObserver.observe(surface);",
  "",
  "window.addEventListener(\"resize\", resize, {passive:true});",
  "window.addEventListener(\"orientationchange\", () => {",
  "  requestAnimationFrame(resize);",
  "  setTimeout(resize, 120);",
  "}, {passive:true});",
  "",
  "if (window.visualViewport) {",
  "  window.visualViewport.addEventListener(\"resize\", resize, {passive:true});",
  "  window.visualViewport.addEventListener(\"scroll\", resize, {passive:true});",
  "}",
  "",
  "window.addEventListener(\"pageshow\", () => {",
  "  requestAnimationFrame(resize);",
  "}, {passive:true});",
  "",
  "document.addEventListener(\"visibilitychange\", () => {",
  "  if (!document.hidden) {",
  "    requestAnimationFrame(resize);",
  "    setTimeout(resize, 80);",
  "  }",
  "}, {passive:true});",
  "",
  "if (memoryStoryScroll) {",
  "  memoryStoryScroll.addEventListener(\"scroll\", () => {",
  "    memoryStoryScroll.classList.toggle(\"is-reading\", memoryStoryScroll.scrollTop > 56);",
  "  }, {passive:true});",
  "}",
  "",
  "// Small public bridge for the presentation layer: photo-book swipes move exactly",
  "// one memory at a time, while the timeline itself keeps its original V16 controls.",
  "window.__taleraPhotoBook = {",
  "  state() {",
  "    const index=Math.max(0,MEMORIES.findIndex(m=>m.id===activeMemoryId));",
  "    const current=MEMORIES[index];",
  "    const previous=MEMORIES[index-1]||null;",
  "    const next=MEMORIES[index+1]||null;",
  "    return {index,current,previous,next};",
  "  },",
  "  step(direction) {",
  "    const index=Math.max(0,MEMORIES.findIndex(m=>m.id===activeMemoryId));",
  "    const targetIndex=clamp(index+direction,0,MEMORIES.length-1);",
  "    const target=MEMORIES[targetIndex];",
  "    if(!target || target.id===activeMemoryId) return false;",
  "    userIsMoving=false;",
  "    centerMs=target.ms;",
  "    keepCenterValid();",
  "    writeMemory(target);",
  "    draw();",
  "    return true;",
  "  }",
  "};",
  "",
  "writeMemory(nearestMemory(centerMs));",
  "resize();",
  "})();",
  "</script>",
  "",
  "",
  "</body>",
  "</html>",
];
