export const topicNames=['familie','vrienden','werk','sport','vrije tijd','jeugd','school en studie','reizen','wonen','relaties','vieringen','gezondheid en zorg','hobby en creativiteit'];
// Evidence is required for extracted entities/times/topics. Unsupported model fields are discarded.
export function cleanAnalysis(value,sourceText){
  const grounded=list=>Array.isArray(list)?list.filter(v=>typeof v==='string'&&v.trim()&&v.length<=120&&sourceText.toLocaleLowerCase('nl').includes(v.trim().toLocaleLowerCase('nl'))).map(v=>v.trim()).slice(0,20):[];
  let topics=Array.isArray(value?.topics)?value.topics.filter(v=>topicNames.includes(v?.name)&&typeof v.evidence==='string'&&v.evidence.trim()&&sourceText.toLowerCase().includes(v.evidence.toLowerCase())).map(v=>({name:v.name,evidence:v.evidence.slice(0,300)})).slice(0,13):[];
  const hints={'familie':/\b(zus|broer|oma|opa|moeder|vader|ouders|kinderen|familie)\b/i,'vrienden':/\b(vrienden|vriend|vriendin)\b/i,'werk':/\b(werk|collega|baan|kantoor)\b/i,'sport':/\b(sport|voetbal|tennis|hardlopen|wedstrijd)\b/i,'vrije tijd':/\b(wandelen|wandelde|wandeling|weekend)\b/i,'jeugd':/\b(jeugd|kindertijd)\b/i,'school en studie':/\b(school|studie|universiteit)\b/i,'reizen':/\b(vakantie|reis|reizen)\b/i,'wonen':/\b(woning|verhuizen|verhuisden)\b/i,'relaties':/\b(partner|trouwen|getrouwd)\b/i,'vieringen':/\b(verjaardag|feest|vierden)\b/i,'gezondheid en zorg':/\b(ziekenhuis|verpleging|operatie)\b/i,'hobby en creativiteit':/\b(schilderen|tekenen|hobby|muziek)\b/i};
  for(const [name,re] of Object.entries(hints)){const match=sourceText.match(re);if(match&&!topics.some(v=>v.name===name))topics.push({name,evidence:match[0]});}
  // A literal source excerpt is a safe brief summary; no new facts can be introduced.
  const summary=typeof value?.summary==='string'&&value.summary.trim()&&sourceText.includes(value.summary.trim())?value.summary.trim().slice(0,500):(sourceText.match(/^[^.!?\n]+[.!?]?/)?.[0]||'').slice(0,500);
  return {version:1,sourceText,generatedAt:Date.now(),persons:grounded(value?.persons),places:grounded(value?.places),timeReferences:[...new Set([...grounded(value?.timeReferences),...(sourceText.match(/\b(?:(?:voorjaar|zomer|herfst|winter)(?: van)?\s+(?:19|20)\d{2}|(?:19|20)\d{2})\b/gi)||[])])],summary,topics};
}
export function cleanTitle(output){const title=String(output||'').replace(/^\s*(titel\s*:\s*)?/i,'').replace(/^["“']|["”']$/g,'').trim().split('\n')[0].replace(/[.!?]+$/,'').trim();const words=title.split(/\s+/);if(words.length<2||words.length>4||title.length>100)throw new Error('Geen korte titel ontvangen');return title;}
