export const icon='<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><rect width="512" height="512" rx="100" fill="#0F2747"/><path d="M112 135h288v62H291v194h-70V197H112z" fill="#F7F4EF"/></svg>';
export const manifest=JSON.stringify({id:'/',name:'TALERA Free',short_name:'TALERA',lang:'nl',start_url:'/',scope:'/',display:'standalone',background_color:'#F7F4EF',theme_color:'#0F2747',icons:[{src:'/icon-192.png',sizes:'192x192',type:'image/png',purpose:'any'},{src:'/icon-512.png',sizes:'512x512',type:'image/png',purpose:'any'}]});
export const experienceCSS=`#freeUpdate{position:fixed;top:8px;left:50%;transform:translateX(-50%);z-index:13000;padding:10px 16px;border:1px solid #DCEAF6;border-radius:18px;background:#0F2747;color:white;font:600 14px system-ui}#freeUpdate[hidden]{display:none}.notice{pointer-events:none!important}#freeAudio{font:14px/1.3 system-ui;width:min(340px,85vw);margin:8px auto;color:white}#freeAudio p{margin:4px 0}#freeAudio audio{width:100%;height:38px}.free-audio-actions{display:flex;gap:8px;justify-content:center}.free-audio-actions button,#freePlayback button{border:1px solid #DCEAF6;border-radius:20px;background:#0F2747;color:white;padding:8px 13px;font:600 14px system-ui}.free-speaking{box-shadow:0 0 0 9px #E7A98B!important}#freePlayback{position:fixed;right:16px;bottom:165px;z-index:31;max-width:300px;color:white;font:14px system-ui}#freePlayback audio{width:min(280px,75vw);height:40px}#freePhotoNav{display:flex;gap:12px;align-items:center;margin-bottom:8px}#freePhotoNav[hidden],#freeAudio [hidden],#freePlayback [hidden]{display:none}#freePlaybackStatus{background:#0F2747;border-radius:10px;max-width:260px;padding:6px}#freePlaybackStatus:empty{display:none}#freeDevice{box-sizing:border-box;width:calc(100% - 32px);max-width:460px;max-height:85dvh;overflow:auto;padding:24px;border:0;border-radius:22px;background:#F7F4EF;color:#0F2747;font:15px/1.5 system-ui}#freeDevice::backdrop{background:#0008}#freeDevice button,#freeDeviceOpen{border:0;border-radius:12px;background:#173851;color:white;padding:12px;font:600 15px system-ui}#freeDeviceOpen{width:100%;margin-bottom:10px}.photo-voice:has(#freeAudio){bottom:205px!important}.photo-voice:has(#freeAudio) .photo-voice-sub{font-size:14px!important}.photo-voice:has(#freeAudio) .photo-mic-halo{transform:scale(.85)}#backupSteps{padding-left:23px}#backupSteps li{margin:10px 0}`;

export const updatePage=`<!doctype html><html lang="nl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TALERA — App bijwerken</title><style>body{margin:0;background:#f7f4ef;color:#0f2747;font:18px system-ui;padding:32px;line-height:1.5}main{max-width:480px;margin:12vh auto}button{background:#163b50;color:white;border:0;border-radius:24px;padding:18px 24px;font:700 18px system-ui;width:100%}button:disabled{opacity:.6}</style><main><h1>TALERA bijwerken</h1><p>Sla je verhaal op en sluit eerst de overige TALERA-tabbladen. Je lokaal bewaarde herinneringen blijven behouden.</p><button id="update">Open de nieuwste app</button><p id="status" role="status"></p></main><script src="/app-update.js"></script></html>`;

export const quietCSS=`
:root{--command-frost-feather:24px!important;--command-glass-tint:transparent!important;--command-glass-blur:5px!important;--command-glass-saturation:1!important}
main .timeline,main .timeline.is-active{background:transparent!important}
main .timeline::before,main .timeline.is-timeline-engaged::before,main .timeline.is-timeline-afterglow::before{background:transparent!important;backdrop-filter:blur(3px)!important;-webkit-backdrop-filter:blur(3px)!important;opacity:1!important}
.memory-space::before,.memory-caption,#memoryCaption{background:transparent!important}
#memoryStoryMore{display:none!important}#memoryStoryScroll{overflow:hidden!important;touch-action:none!important}
.memory-caption{padding-bottom:110px!important;text-shadow:0 1px 6px #0008!important}
#freeReader{position:fixed;z-index:40;left:0;right:0;bottom:calc(76px + env(safe-area-inset-bottom));box-sizing:border-box;background:#f7f4ef;color:#0f2747;border-radius:24px 24px 0 0;display:flex;flex-direction:column;font:18px/1.6 system-ui;overflow:hidden}
#freeReadHandle{background:transparent;border:0;min-height:38px;width:100%;touch-action:none;flex-shrink:0;cursor:grab}#freeReadHandle span{display:block;margin:auto;width:46px;height:5px;background:#b7bec4;border-radius:4px}
#freeReadText{margin:0;padding:8px 24px 30px;overflow:auto;white-space:pre-wrap;touch-action:pan-y;overscroll-behavior:contain}
.free-close{position:sticky;top:0;float:right;z-index:2;border:0!important;border-radius:50%!important;width:44px!important;height:44px!important;padding:0!important;margin:0 0 8px 8px!important;background:#e4ebef!important;color:#0f2747!important;font:32px system-ui!important;cursor:pointer}
#freeStorageClose,#freeDeviceClose{display:none!important}#freeListenMode{padding:12px;border:0;border-radius:12px;background:#173851;color:white;font:600 15px system-ui}
#freeTimeKind,#freeSeason,#freeSeasonYear{box-sizing:border-box;max-width:100%;padding:12px;margin:8px 0;font:inherit;border:1px solid #cbd5dd;border-radius:12px;background:white;color:#173851}#freeSeasonFields[hidden],#editDate[hidden]{display:none}
.photo-voice-sub{display:none!important}#freeAudioStatus{font-size:12px;max-width:300px;margin:auto!important}#freeAudioPlayer{height:32px!important}
`;
