import {photoFingerprint,photoDate} from './photos.js';
import {compactPhoto} from './media.js';
import {chooseTime,checkedTime,installDateStyle} from './date-picker.js';
import {timeLabel} from './dates.browser.js';

export const batchLimit=25;
export const audioReferences=story=>[...new Set([story.audioId,...(story.audioIds||[])].filter(Boolean))];
export function newPhotoStory(photos,time,batchId){return {id:crypto.randomUUID(),title:'',storyText:'',photos,currentIndex:0,status:'published',createdAt:Date.now(),postedAt:Date.now(),importBatchId:batchId,...checkedTime(time)};}
export async function prepareBatch(files,stories,{compact=compactPhoto,fingerprint=photoFingerprint,capture=photoDate,progress=()=>{}}={}){
  if(!files.length||files.length>batchLimit)throw Error('Kies één tot maximaal 25 foto’s.');
  const known=new Set(stories.flatMap(s=>s.photos||[]).map(p=>p.fingerprint).filter(Boolean)),entries=[],failures=[];let duplicates=0;
  for(const [index,file] of Array.from(files).entries()){
    try{
      if(!(file.type.startsWith('image/')||/\.(heic|heif|jpe?g|png|webp|gif|avif)$/i.test(file.name)))throw Error('Kies een foto; video’s voeg je afzonderlijk toe.');
      if(file.size>64*1024*1024)throw Error('Deze foto is te groot.');
      const hash=await fingerprint(file);if(known.has(hash)){duplicates++;continue;}
      const media=await compact(file,crypto.randomUUID());let date=await capture(file);try{if(date)checkedTime({date});}catch{date='';}
      const photo={id:media.id,kind:'photo',name:file.name||'Foto',type:media.blob.type,fingerprint:hash,captureDate:date,createdAt:Date.now()};entries.push({media,photo,time:date?checkedTime({date}):null});known.add(hash);
    }catch(error){failures.push({name:file.name||'Foto',error:error.message});}
    finally{progress(index+1,files.length);}
  }
  return {entries,duplicates,failures};
}
export function batchGroups(entries){const groups=new Map();for(const entry of entries){if(!entry.time)continue;const key=JSON.stringify(entry.time);if(!groups.has(key))groups.set(key,{key,time:entry.time,entries:[]});groups.get(key).entries.push(entry);}return [...groups.values()];}
export function buildBatch(batch,stories,targets=new Map()){
  if(!batch.entries.length||batch.entries.some(e=>!e.time))throw Error('Geef iedere foto een datum of periode.');
  const id=crypto.randomUUID(),changes=new Map(),expected={},groups=[];
  for(const group of batchGroups(batch.entries)){
    const targetId=targets.get(group.key);let story;
    if(targetId){const saved=stories.find(s=>s.id===targetId&&s.status==='published');if(!saved)throw Error('Dit bestaande verhaal is niet meer beschikbaar.');expected[saved.id]=saved.updatedAt;story=changes.get(saved.id)||structuredClone(saved);story.photos.push(...group.entries.map(e=>e.photo));}
    else story=newPhotoStory(group.entries.map(e=>e.photo),group.time,id);
    changes.set(story.id,story);groups.push({storyId:story.id,photoIds:group.entries.map(e=>e.photo.id),time:group.time});
  }
  return {changes:[...changes.values()],media:batch.entries.map(e=>e.media),expected,summary:{id:'last',batchId:id,createdAt:Date.now(),duplicates:batch.duplicates,failures:batch.failures,groups}};
}
export function installImportStyle(){if(document.getElementById('freeImportStyle'))return;const s=document.createElement('style');s.id='freeImportStyle';s.textContent='.free-import-dialog{box-sizing:border-box;width:calc(100% - 16px);max-width:720px;max-height:calc(100dvh - 16px);border:0;border-radius:24px;padding:20px;background:white;color:#173851;font:16px/1.5 system-ui;overflow:auto}.free-import-dialog::backdrop{background:#071b2e88}.free-import-dialog h2{margin:0 0 12px;font-size:23px}.free-import-dialog h3{font-size:17px;margin:16px 0 8px}.free-import-dialog button{border:0;border-radius:12px;padding:12px;background:#e8eef2;color:#173851;font:inherit;cursor:pointer}.free-import-dialog button.primary{background:#173851;color:white}.free-import-dialog button:disabled{opacity:.45}.free-import-dialog [hidden]{display:none!important}.free-import-dialog .tiles{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.free-import-dialog .tile{position:relative;width:82px;height:82px;display:block;overflow:hidden;border-radius:12px;background:#e8eef2}.free-import-dialog .tile img{width:100%;height:100%;object-fit:cover}.free-import-dialog .tile input{position:absolute;top:5px;right:5px;width:22px;height:22px;accent-color:#173851}.free-import-dialog select{box-sizing:border-box;width:100%;padding:12px;border:1px solid #cad6df;border-radius:12px;background:white;color:#173851;font:inherit;margin:8px 0}.free-import-dialog .actions{display:flex;gap:8px;flex-wrap:wrap;position:sticky;bottom:-20px;padding:12px 0 20px;background:white}.free-import-dialog [role=status]{font-size:14px}.free-import-dialog .group{border-top:1px solid #dbe3e9;padding-top:8px}.free-import-dialog label{display:block}.free-import-dialog .close{float:right;border-radius:50%;width:44px;height:44px;padding:0;font-size:28px}';document.head.append(s);}
export function installBulkImport({storage,exclusive,onSaved=async id=>{location.hash='story='+encodeURIComponent(id);location.reload();}}){
  installDateStyle();installImportStyle();
  const dialog=document.createElement('dialog');dialog.className='free-import-dialog';dialog.id='freeBulkImport';dialog.setAttribute('aria-labelledby','freeBulkHeading');dialog.innerHTML='<button class="close free-close" aria-label="Import sluiten">×</button><h2 id="freeBulkHeading">Foto’s op je tijdlijn</h2><p>Kies maximaal 25 foto’s. We delen ze per opnamedag in. Je kunt later altijd anders indelen.</p><input type="file" accept="image/*" multiple hidden><div data-last></div><button data-choose>Foto’s kiezen</button><p role="status" aria-live="polite"></p><div data-groups></div><div class="actions"><button data-save class="primary" hidden>Op mijn tijdlijn</button><button data-next hidden>Nog 25 toevoegen</button><button data-view hidden>Bekijk je tijdlijn</button></div>';document.body.append(dialog);
  const file=dialog.querySelector('input'),status=dialog.querySelector('[role=status]'),body=dialog.querySelector('[data-groups]'),save=dialog.querySelector('[data-save]'),choose=dialog.querySelector('[data-choose]'),next=dialog.querySelector('[data-next]'),view=dialog.querySelector('[data-view]'),last=dialog.querySelector('[data-last]');let batch=null,stories=[],targets=new Map(),urls=[],busy=false,focusId='';
  function release(){urls.forEach(URL.revokeObjectURL);urls=[];}
  async function tiles(container,entries,selectable=false){const grid=document.createElement('div');grid.className='tiles';container.append(grid);for(const entry of entries){const label=document.createElement('label');label.className='tile';const img=document.createElement('img');img.alt=entry.photo.name||'Foto';const url=URL.createObjectURL(entry.media.thumbnail||entry.media.blob);urls.push(url);img.src=url;label.append(img);if(selectable){const check=document.createElement('input');check.type='checkbox';check.setAttribute('aria-label','Selecteer '+img.alt);check.dataset.id=entry.photo.id;label.append(check);}grid.append(label);}}
  async function paint(){release();body.replaceChildren();last.hidden=true;const unknown=batch.entries.filter(e=>!e.time);if(unknown.length){const section=document.createElement('section');const h=document.createElement('h3');h.textContent='Voeg een datum of periode toe';section.append(h);await tiles(section,unknown,true);const all=document.createElement('button');all.textContent='Alle foto’s zonder datum selecteren';all.onclick=()=>section.querySelectorAll('input').forEach(c=>c.checked=true);const date=document.createElement('button');date.textContent='Datum of periode kiezen';date.onclick=async()=>{const ids=new Set([...section.querySelectorAll('input:checked')].map(c=>c.dataset.id));if(!ids.size){status.textContent='Selecteer eerst de foto’s die bij elkaar horen.';return;}const time=await chooseTime({},'Voeg een datum of periode toe');if(time){batch.entries.filter(e=>ids.has(e.photo.id)).forEach(e=>e.time=time);await paint();}};section.append(all,date);body.append(section);}
    for(const group of batchGroups(batch.entries)){const section=document.createElement('section');section.className='group';const h=document.createElement('h3');h.textContent=timeLabel(group.time)+' · '+group.entries.length+' foto’s';section.append(h);await tiles(section,group.entries);const date=document.createElement('button');date.textContent='Datum aanpassen';date.onclick=async()=>{const time=await chooseTime(group.time);if(time){targets.delete(group.key);group.entries.forEach(e=>e.time=time);await paint();}};section.append(date);const existing=stories.filter(s=>s.status==='published'&&group.time.date&&s.date===group.time.date);if(existing.length){const label=document.createElement('label');label.textContent='Er staat al een verhaal op deze dag.';const select=document.createElement('select');select.setAttribute('aria-label','Foto’s van '+timeLabel(group.time)+' plaatsen');const option=document.createElement('option');option.value='';option.textContent='Als apart verhaal toevoegen';select.append(option);for(const s of existing){const o=document.createElement('option');o.value=s.id;o.textContent='Toevoegen aan '+(s.title||timeLabel(s));select.append(o);}select.value=targets.get(group.key)||'';select.onchange=()=>targets.set(group.key,select.value);label.append(select);section.append(label);}body.append(section);}
    status.textContent=`${batch.entries.length} nieuw · ${batch.duplicates} al aanwezig${batch.failures.length?' · '+batch.failures.length+' niet verwerkt':''}.`;
    for(const fail of batch.failures){const p=document.createElement('p');p.textContent=fail.name+': '+fail.error;body.append(p);}save.hidden=!batch.entries.length;save.disabled=busy||unknown.length>0;
  }
  async function summary(){release();last.replaceChildren();const saved=await storage.lastImport();if(!saved)return;const h=document.createElement('h3');h.textContent='Je laatste import';last.append(h);for(const group of saved.groups||[]){const p=document.createElement('p');p.textContent=timeLabel(group.time)+' · '+group.photoIds.length+' foto’s';last.append(p);const entries=[];for(const id of group.photoIds){const media=await storage.media(id);if(media)entries.push({media,photo:{id,name:'Geïmporteerde foto'}});}await tiles(last,entries);}last.hidden=false;}
  async function open(){if(dialog.open)return;focusId='';batch=null;targets=new Map();body.replaceChildren();status.textContent='';save.hidden=next.hidden=view.hidden=true;choose.hidden=false;await summary();dialog.showModal();}
  choose.onclick=next.onclick=()=>{if(!busy)file.click();};
  file.onchange=async()=>{const files=Array.from(file.files||[]);file.value='';if(!files.length)return;batch=null;release();body.replaceChildren();busy=true;choose.disabled=next.disabled=true;save.hidden=next.hidden=view.hidden=true;try{stories=await storage.stories();targets=new Map();status.textContent='Je foto’s verwerken…';batch=await prepareBatch(files,stories,{progress:(n,total)=>status.textContent=`${n} / ${total} verwerken…`});await paint();if(!batch.entries.length){next.hidden=false;view.hidden=false;}}catch(error){status.textContent=error.message;}finally{busy=false;choose.disabled=next.disabled=false;if(batch)save.disabled=batch.entries.some(e=>!e.time);}};
  save.onclick=async()=>{if(busy)return;busy=true;save.disabled=true;status.textContent='Je herinneringen bewaren…';try{const plan=buildBatch(batch,stories,targets);await exclusive(()=>storage.saveCollection(plan.changes,plan.media,plan.expected,plan.summary));focusId=plan.changes[0].id;batch=null;body.replaceChildren();save.hidden=choose.hidden=true;next.hidden=view.hidden=false;await summary();status.textContent=`${plan.media.length} foto’s toegevoegd · ${plan.summary.duplicates} dubbelen overgeslagen.${plan.summary.failures.length?' '+plan.summary.failures.length+' foto’s zijn niet verwerkt; je kunt ze opnieuw kiezen.':''}`;}catch(error){status.textContent=error.message;}finally{busy=false;save.disabled=false;}};
  view.onclick=()=>onSaved(focusId);dialog.querySelector('.close').onclick=()=>{if(busy){status.textContent='Even wachten tot je foto’s verwerkt zijn.';return;}dialog.close();release();};dialog.oncancel=e=>{e.preventDefault();dialog.querySelector('.close').click();};window.addEventListener('beforeunload',e=>{if(dialog.open&&(busy||batch?.entries.length)){e.preventDefault();e.returnValue='';}});
  const menu=document.getElementById('freeStorageInfo'),button=document.createElement('button');button.id='freeBulkOpen';button.textContent='Foto’s importeren · maximaal 25';button.style.cssText='width:100%;padding:12px;margin-bottom:10px;border:0;border-radius:12px;background:#173851;color:white;font:inherit';button.onclick=()=>{menu?.close();open().catch(e=>status.textContent=e.message);};menu?.insertBefore(button,menu.querySelector('p'));
  const empty=document.getElementById('freeEmpty');if(empty){const entry=document.createElement('button');entry.textContent='Foto’s importeren';entry.onclick=()=>open();empty.append(entry);}
  return {open};
}
