export const nl={
  audioLater:'Lokale audio volgt in de volgende proefstap. Je kunt nu je verhaal typen.',
  localNotice:'Je herinneringen staan op dit toestel. TALERA bewaart hiervan geen cloudkopie.',
  pickerHelp:'Tik op + foto, kies één foto en bevestig in je fotobibliotheek met Voeg toe, Open of Gereed.',
  storageTitle:'Foto’s op dit toestel',
  storageSteps:'Je hoeft geen map aan te maken of maptoegang te geven. Na je keuze maakt TALERA automatisch een compacte kopie in de browseropslag. Je originele foto blijft in je fotobibliotheek.',
  storageNext:'Voeg daarna een datum en tekst toe en tik op Op mijn tijdlijn. Open TALERA later op hetzelfde toestel en in dezelfde browser.',
  storageWarning:'Gebruik een gewone Safari-tab, geen privétab. Wis je websitegegevens, dan kun je deze herinneringen verliezen. Er is nog geen reservekopie of overdracht naar een ander toestel.',
  storageClose:'Begrepen',
  firstMemory:'Maak je eerste herinnering',editMemory:'Herinnering bewerken',
  write:'Tik om je tekst te schrijven',writePhoto:'Tik en schrijf',writeMore:'Schrijf verder',
  photoPrompt:'Kijk naar je foto en schrijf wat er gebeurde',saveTimeline:'Op mijn tijdlijn',saving:'Lokaal bewaren…',
  savePhotoError:'Foto lokaal bewaren lukte niet · probeer opnieuw',onePhoto:'Deze eerste proef bewaart één foto per herinnering',
  closeTabs:'Sluit andere TALERA-tabbladen en probeer opnieuw.',storageUnavailable:'Lokale opslag is niet beschikbaar.',
  photoProcessingError:'Foto kon niet lokaal worden verwerkt.',photoReadError:'Foto kon niet worden teruggelezen.',
  invalidMemory:'Ongeldige herinnering.',memoryReadError:'Herinnering kon niet worden teruggelezen.',
  unsupportedPhoto:'Dit fotoformaat kan hier niet worden geopend. Kies een JPEG- of PNG-foto.',
  localOnly:'Deze proef gebruikt uitsluitend lokale inhoud.',choosePhotoDate:'Kies een foto en bevestig de datum.',
  writeFirst:'Schrijf eerst je herinnering.',later:'Deze functie volgt in een volgende proefstap.',
  storageFull:'De lokale opslag is vol. Je eerdere herinneringen blijven bewaard.',missingPhoto:'Een lokale foto ontbreekt.'
};
