export const nl={
  updateReady:'Nieuwe versie klaar · Bijwerken',
  audioTitle:'Gesproken herinnering',audioStart:'Tik en vertel',audioStop:'Stop en bewaar',audioPause:'Pauze',audioResume:'Verder vertellen',typeInstead:'Typ liever',
  audioReady:'Je microfoon staat uit.',audioPermission:'Microfoon openen…',audioRecording:'Je stem wordt opgenomen op dit toestel.',audioPaused:'Opname gepauzeerd.',audioSaving:'Opname lokaal bewaren…',audioSaved:'Opname bewaard. Je kunt terugluisteren.',
  audioLocalHelp:'Vertel bij je foto. Je opname blijft op dit toestel; tekst kun je zelf typen.',audioUnsupported:'Deze browser kan niet opnemen. Je kunt wel foto’s kiezen en je verhaal typen.',audioDenied:'Microfoontoegang geweigerd. Sta de microfoon toe in je browserinstellingen, of kies Typ liever.',audioMissing:'Er is geen beschikbare microfoon gevonden.',audioFailed:'Opnemen of bewaren lukte niet. Je eerdere herinnering blijft bewaard.',audioEmpty:'Er is geen geluid opgenomen. Probeer opnieuw.',audioFinishFirst:'Stop en bewaar eerst je opname.',audioInterrupted:'Deze opname is onderbroken. Luister terug; mogelijk ontbreekt het laatste stukje.',audioReplace:'Een nieuwe opname vervangt je huidige opname zodra die wordt bewaard. Wil je opnieuw opnemen?',
  listen:'Luister naar je verhaal',previousPhoto:'Vorige foto',nextPhoto:'Volgende foto',deleteMemory:'Herinnering verwijderen',deleteConfirm:'Deze herinnering uit TALERA verwijderen? Je originele foto’s blijven in je fotobibliotheek. Maak eerst een reservekopie als je haar wilt bewaren.',
  deviceTitle:'Installatie en opslag',deviceHelp:'Op iPhone: open TALERA in Safari, tik op Delen en kies Zet op beginscherm. Open daarna het TALERA-icoon en voeg daar je herinneringen toe. Is die tijdlijn leeg? Zet je reservekopie terug: Safari en de app kunnen aparte opslag gebruiken. Op Android vind je Installeren of Toevoegen aan startscherm in het browsermenu.',offlineReady:'De app is voorbereid voor offlinegebruik.',offlinePending:'Offlinevoorbereiding is nog niet afgerond. Houd TALERA even online geopend.',protectStorage:'Vraag om opslag te behouden',storageUsed:'browseropslag gebruikt.',storageEstimateMissing:'Deze browser toont geen opslagmeting.',storageProtected:'De browser heeft het bewaren van opslag toegestaan. Een reservekopie blijft nodig.',storageNotProtected:'Deze browser geeft geen extra opslaggarantie. Maak zelf reservekopieën.',
  photoLimit:'Kies maximaal 12 foto’s per herinnering in deze proef.',photoTooLarge:'Deze foto is te groot om hier veilig te verwerken. Kies een bestand tot 64 MB.',photoProgress:'foto’s lokaal bewaard',photoDuplicate:'al eerder gekozen',photoFailedCount:'niet verwerkt',noPhoto:'Geen bruikbare foto geselecteerd.',photoDateFound:'Er staat een opnamedatum in deze foto. Controleer en bevestig die datum.',unknownDate:'Datum onbekend',unknownTimelineDate:'Datum onbekend · voorlopig bij het moment van toevoegen geplaatst.',
  backupTitle:'Reservekopie',backupMake:'Reservekopie maken',backupRestore:'Reservekopie terugzetten',backupLater:'Later',backupClose:'Sluiten',
  backupIntro:'TALERA bewaart een kleine kopie van je geselecteerde foto op dit toestel, zodat je tijdlijn werkt.',
  backupExplanation:'Bewaar je foto’s en verhalen ook in Bestanden. Met die reservekopie kun je je tijdlijn terugzetten tot het moment waarop de kopie is gemaakt.',
  backupWorking:'Je volledige collectie wordt klaargezet…',backupReady:'Je reservekopie staat klaar. In het volgende venster kies je waar je het bestand bewaart.',
  backupIOSReady:'Je reservekopie staat klaar. Je iPhone toont straks verschillende apps. Volg deze drie stappen om de kopie op je telefoon te bewaren:',
  backupIOSStep1:'Tik hieronder op Open bewaarvenster.',backupIOSStep2:'Veeg in het menu omhoog en tik op Bewaar in Bestanden.',backupIOSStep3:'Kies Op mijn iPhone en tik op Bewaar. Een aparte map aanmaken hoeft niet.',
  backupIOSConfirm:'Heb je in Bestanden op Bewaar getikt?',
  backupSave:'Open bewaarvenster',backupDownload:'Download reservekopie',backupDownloadHelp:'Download je reservekopie. Je browser gebruikt de ingestelde downloadmap of vraagt waar je het bestand wilt bewaren. Het bestand bevat je volledige collectie.',
  backupConfirm:'Is het bestand bewaard?',backupYes:'Ja, bestand bewaard',backupNotYet:'Nog niet',
  backupConfirmed:'Bewaren door jou bevestigd op: ',backupPrepared:'Kopie voorbereid op: ',backupOutdated:'Er zijn wijzigingen sinds je laatste bevestigde kopie. Maak een nieuwe kopie om die mee te nemen.',
  backupNone:'Nog geen bewaarde reservekopie bevestigd.',backupSnapshot:'Elke kopie bevat je volledige collectie van dat moment. Nieuwe wijzigingen komen mee bij de volgende kopie.',
  backupCancelled:'Bewaren geannuleerd. Je herinneringen op dit toestel blijven staan.',backupShareFailed:'Het systeemmenu kon niet worden geopend. Je kunt het bestand ook downloaden.',
  backupChecking:'Reservekopie controleren…',backupReplace:'Terugzetten vervangt alle huidige herinneringen op dit toestel door de collectie uit dit bestand. Nieuwe wijzigingen die niet in deze kopie staan, komen niet mee. Maak zo nodig eerst een kopie van je huidige collectie.',
  backupApply:'Vervang en zet terug',backupImportReady:'Gecontroleerde reservekopie: ',backupRestoring:'Herinneringen terugzetten…',backupCounts:'herinneringen · foto’s',
  backupInvalid:'Dit bestand is geen geldige, volledige TALERA-reservekopie. Je huidige herinneringen blijven staan.',backupUnsupported:'Deze versie van de reservekopie wordt nog niet ondersteund.',
  backupTooLarge:'Deze proef ondersteunt reservekopieën tot 256 MB. Je huidige herinneringen blijven staan.',backupEmpty:'Voeg eerst een herinnering toe voordat je een reservekopie maakt.',
  backupFailure:'Dit lukte niet. Je huidige herinneringen blijven staan. Probeer opnieuw.',

  audioLater:'Lokale audio volgt in de volgende proefstap. Je kunt nu je verhaal typen.',
  localNotice:'Je herinneringen staan op dit toestel. TALERA bewaart hiervan geen cloudkopie.',
  pickerHelp:'Tik op + foto, kies maximaal 12 foto’s en bevestig in je fotobibliotheek met Voeg toe, Open of Gereed.',
  storageTitle:'Foto’s op dit toestel',
  storageSteps:'Je hoeft geen map aan te maken of maptoegang te geven. Na je keuze maakt TALERA automatisch een compacte kopie in de browseropslag. Je originele foto blijft in je fotobibliotheek.',
  storageNext:'Voeg daarna een datum en tekst of opname toe en tik op Op mijn tijdlijn. Open TALERA later op hetzelfde toestel en in dezelfde browser.',
  storageWarning:'Gebruik een gewone Safari-tab, geen privétab. Wis je websitegegevens, dan kun je deze herinneringen verliezen. Bewaar daarom een reservekopie via Meer → Reservekopie.',
  storageClose:'Begrepen',
  firstMemory:'Maak je eerste herinnering',editMemory:'Herinnering bewerken',
  write:'Tik om je tekst te schrijven',writePhoto:'Tik en schrijf',writeMore:'Schrijf verder',
  photoPrompt:'Kijk naar je foto en schrijf wat er gebeurde',saveTimeline:'Op mijn tijdlijn',saving:'Lokaal bewaren…',
  savePhotoError:'Foto lokaal bewaren lukte niet · probeer opnieuw',onePhoto:'Deze eerste proef bewaart één foto per herinnering',
  closeTabs:'Sluit andere TALERA-tabbladen en probeer opnieuw.',storageUnavailable:'Lokale opslag is niet beschikbaar.',
  photoProcessingError:'Foto kon niet lokaal worden verwerkt.',photoReadError:'Foto kon niet worden teruggelezen.',
  invalidMemory:'Ongeldige herinnering.',memoryReadError:'Herinnering kon niet worden teruggelezen.',
  unsupportedPhoto:'Dit fotoformaat kan hier niet worden geopend. Kies een JPEG- of PNG-foto.',
  localOnly:'Deze proef gebruikt uitsluitend lokale inhoud.',choosePhotoDate:'Kies een foto en bevestig de datum.',
  photoBusy:'De foto wordt nog bewaard. Wacht even en probeer opnieuw.',
  addDate:'Voeg eerst de datum van je herinnering toe.',
  writeFirst:'Schrijf eerst je herinnering.',later:'Deze functie volgt in een volgende proefstap.',
  storageFull:'De lokale opslag is vol. Je eerdere herinneringen blijven bewaard.',missingPhoto:'Een lokale foto ontbreekt.'
};
