export const nl={
  backupTitle:'Reservekopie',backupMake:'Reservekopie maken',backupRestore:'Reservekopie terugzetten',backupLater:'Later',backupClose:'Sluiten',
  backupIntro:'TALERA bewaart een kleine kopie van je geselecteerde foto op dit toestel, zodat je tijdlijn werkt.',
  backupExplanation:'Bewaar je foto’s en verhalen ook in Bestanden. Met die reservekopie kun je je tijdlijn terugzetten tot het moment waarop de kopie is gemaakt.',
  backupWorking:'Je volledige collectie wordt klaargezet…',backupReady:'Je reservekopie staat klaar. Bewaar het bestand in Bestanden, bijvoorbeeld in een map TALERA onder Op mijn iPhone. Kies een lokale plek als je geen cloudopslag wilt.',
  backupSave:'Bewaar reservekopie',backupDownload:'Download reservekopie',backupDownloadHelp:'Je browser kan dit bestand niet rechtstreeks delen. Download het bestand en bewaar het in Bestanden. De download bevat je volledige collectie.',
  backupConfirm:'Is het bestand bewaard?',backupYes:'Ja, bestand bewaard',backupNotYet:'Nog niet',
  backupConfirmed:'Bewaren door jou bevestigd op: ',backupPrepared:'Kopie voorbereid op: ',backupOutdated:'Er zijn wijzigingen sinds je laatste bevestigde kopie. Maak een nieuwe kopie om die mee te nemen.',
  backupNone:'Nog geen bewaarde reservekopie bevestigd.',backupSnapshot:'Elke kopie bevat je volledige collectie van dat moment. Nieuwe wijzigingen komen mee bij de volgende kopie.',
  backupCancelled:'Bewaren geannuleerd. Je herinneringen op dit toestel blijven staan.',backupShareFailed:'Het systeemmenu kon niet worden geopend. Je kunt het bestand ook downloaden.',
  backupChecking:'Reservekopie controleren…',backupReplace:'Terugzetten vervangt alle huidige herinneringen op dit toestel door de collectie uit dit bestand. Nieuwe wijzigingen die niet in deze kopie staan, komen niet mee. Maak zo nodig eerst een kopie van je huidige collectie.',
  backupApply:'Vervang en zet terug',backupImportReady:'Gecontroleerde reservekopie: ',backupRestoring:'Herinneringen terugzetten…',backupCounts:'herinneringen · foto’s',
  backupInvalid:'Dit bestand is geen geldige, volledige TALERA-reservekopie. Je huidige herinneringen blijven staan.',backupUnsupported:'Deze versie van de reservekopie wordt nog niet ondersteund.',
  backupTooLarge:'Deze proef ondersteunt reservekopieën tot 256 MB. Je huidige herinneringen blijven staan.',backupEmpty:'Voeg eerst een herinnering toe voordat je een reservekopie maakt.',
  backupFailure:'Dit lukte niet. Je huidige herinneringen blijven staan. Probeer opnieuw.',

  audioLater:'Lokale audio volgt in de volgende proefstap. Je kunt nu je verhaal typen.',
  localNotice:'Je herinneringen staan op dit toestel. TALERA bewaart hiervan geen cloudkopie.',
  pickerHelp:'Tik op + foto, kies één foto en bevestig in je fotobibliotheek met Voeg toe, Open of Gereed.',
  storageTitle:'Foto’s op dit toestel',
  storageSteps:'Je hoeft geen map aan te maken of maptoegang te geven. Na je keuze maakt TALERA automatisch een compacte kopie in de browseropslag. Je originele foto blijft in je fotobibliotheek.',
  storageNext:'Voeg daarna een datum en tekst toe en tik op Op mijn tijdlijn. Open TALERA later op hetzelfde toestel en in dezelfde browser.',
  storageWarning:'Gebruik een gewone Safari-tab, geen privétab. Wis je websitegegevens, dan kun je deze herinneringen verliezen. Bewaar daarom een reservekopie via Meer → Reservekopie.',
  storageClose:'Begrepen',
  firstMemory:'Maak je eerste herinnering',editMemory:'Herinnering bewerken',
  write:'Tik om je tekst te schrijven',writePhoto:'Tik en schrijf',writeMore:'Schrijf verder',
  photoPrompt:'Kijk naar je foto en schrijf wat er gebeurde',saveTimeline:'Op mijn tijdlijn',saving:'Lokaal bewaren…',
  savePhotoError:'Foto lokaal bewaren lukte niet · probeer opnieuw',onePhoto:'Deze eerste proef bewaart één foto per herinnering',
  closeTabs:'Sluit andere TALERA-tabbladen en probeer opnieuw.',storageUnavailable:'Lokale opslag is niet beschikbaar.',
  photoProcessingError:'Foto kon niet lokaal worden verwerkt.',photoReadError:'Foto kon niet worden teruggelezen.',
  invalidMemory:'Ongeldige herinnering.',memoryReadError:'Herinnering kon niet worden teruggelezen.',
  unsupportedPhoto:'Dit fotoformaat kan hier niet worden geopend. Kies een JPEG- of PNG-foto.',
  localOnly:'Deze proef gebruikt uitsluitend lokale inhoud.',choosePhotoDate:'Kies een foto en bevestig de datum.',
  photoBusy:'De foto wordt nog bewaard. Wacht even en probeer opnieuw.',
  addDate:'Voeg eerst de datum van je herinnering toe.',
  writeFirst:'Schrijf eerst je herinnering.',later:'Deze functie volgt in een volgende proefstap.',
  storageFull:'De lokale opslag is vol. Je eerdere herinneringen blijven bewaard.',missingPhoto:'Een lokale foto ontbreekt.'
};
