import {validTime,seasonTime,seasons} from './dates.browser.js';
export function checkedTime(value){
  if(!validTime(value))throw Error('Kies een datum of een seizoen met jaartal.');
  const today=new Date();if(value.date&&value.date>today.toISOString().slice(0,10)||value.eventTime&&new Date(value.eventTime.year,seasons[value.eventTime.season][0],1)>today)throw Error('Kies een datum of tijdvak dat al is begonnen.');
  return {...value,datePrecision:value.eventTime?'season':'day'};
}
export function chooseTime(initial={},heading='Wanneer gebeurde dit verhaal?'){
  const dialog=document.createElement('dialog');dialog.className='free-time-dialog';
  dialog.innerHTML='<h2></h2><div class="free-time-choices"><button type="button" data-kind="day">Exacte datum</button><button type="button" data-kind="season">Seizoen en jaartal</button></div><section class="free-calendar" hidden><div class="free-month"><button type="button" aria-label="Vorige maand">‹</button><input type="month" aria-label="Maand en jaar"><button type="button" aria-label="Volgende maand">›</button></div><div class="free-days"></div></section><section class="free-season" hidden><select aria-label="Seizoen"><option value="voorjaar">Voorjaar</option><option value="zomer">Zomer</option><option value="herfst">Herfst</option><option value="winter">Winter</option></select><input type="number" min="1" max="9999" aria-label="Jaartal" placeholder="Jaartal"></section><p role="status"></p><div class="free-time-actions"><button type="button" data-cancel>Annuleren</button><button type="button" data-save>Verder</button></div>';
  document.body.append(dialog);dialog.querySelector('h2').textContent=heading;
  let kind=initial.eventTime?'season':'day',date=initial.date||'',month=(date||(initial.eventTime?String(initial.eventTime.year).padStart(4,'0')+'-'+String({voorjaar:3,zomer:6,herfst:9,winter:1}[initial.eventTime.season]).padStart(2,'0'):new Date().toISOString())).slice(0,7);
  const monthInput=dialog.querySelector('[type=month]'),season=dialog.querySelector('select'),year=dialog.querySelector('[type=number]');season.value=initial.eventTime?.season||'zomer';year.value=initial.eventTime?.year||'';
  function paint(){dialog.querySelector('.free-calendar').hidden=kind!=='day';dialog.querySelector('.free-season').hidden=kind!=='season';dialog.querySelectorAll('[data-kind]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kind===kind)));monthInput.value=month;const days=dialog.querySelector('.free-days');days.replaceChildren();for(const name of ['ma','di','wo','do','vr','za','zo']){const label=document.createElement('span');label.textContent=name;days.append(label);}const [y,m]=month.split('-').map(Number),start=new Date(y,m-1,1),count=new Date(y,m,0).getDate();for(let i=0;i<(start.getDay()+6)%7;i++)days.append(document.createElement('span'));for(let n=1;n<=count;n++){const value=month+'-'+String(n).padStart(2,'0'),b=document.createElement('button');b.type='button';b.textContent=n;b.disabled=value>new Date().toISOString().slice(0,10);b.setAttribute('aria-label',value);b.setAttribute('aria-pressed',String(date===value));b.onclick=()=>{date=value;paint();};days.append(b);}}
  dialog.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;paint();});monthInput.onchange=()=>{if(monthInput.value){month=monthInput.value;paint();}};dialog.querySelectorAll('.free-month button').forEach((b,i)=>b.onclick=()=>{const [y,m]=month.split('-').map(Number),d=new Date(y,m-1+(i?1:-1),1,12);month=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');paint();});
  return new Promise(resolve=>{const finish=value=>{dialog.close();dialog.remove();resolve(value);};dialog.oncancel=e=>{e.preventDefault();finish(null);};dialog.querySelector('[data-cancel]').onclick=()=>finish(null);dialog.querySelector('[data-save]').onclick=()=>{try{finish(checkedTime(kind==='day'?{date,eventTime:undefined}:{date:'',eventTime:seasonTime(season.value,Number(year.value))}));}catch(e){dialog.querySelector('[role=status]').textContent=e.message;}};paint();dialog.showModal();});
}
export function installDateStyle(){if(document.getElementById('freeDateStyle'))return;const style=document.createElement('style');style.id='freeDateStyle';style.textContent='.free-time-dialog,#freeOverview,#freeStoryMenu{box-sizing:border-box;width:calc(100% - 24px);max-width:540px;max-height:90dvh;overflow:auto;border:0;border-radius:22px;padding:22px;background:#fff;color:#173851;font:16px/1.5 system-ui}.free-time-dialog::backdrop,#freeOverview::backdrop,#freeStoryMenu::backdrop{background:#0006}.free-time-dialog button,#freeOverview button,#freeStoryMenu button{cursor:pointer;border:0;border-radius:14px;padding:12px;background:#e9eef2;color:#173851;font:inherit}.free-time-choices,.free-time-actions,.free-month{display:flex;gap:8px;margin:12px 0}.free-time-dialog button[aria-pressed=true]{background:#173851;color:white}.free-days{display:grid;grid-template-columns:repeat(7,1fr);gap:3px;text-align:center}.free-days button{padding:10px 0}.free-time-dialog [hidden]{display:none}.free-time-dialog input,.free-time-dialog select,#freeOverview input,#freeOverview textarea{box-sizing:border-box;width:100%;padding:12px;border:1px solid #cbd5dd;border-radius:12px;background:white;color:#173851;font:inherit}.free-time-dialog button:disabled{opacity:.3}.free-month input{min-width:0}.free-season{display:flex;gap:8px}';document.head.append(style);}
