import {installImportStyle,audioReferences,newPhotoStory} from './bulk.js';
import {chooseTime} from './date-picker.js';
import {timeLabel} from './dates.browser.js';

export function planPhotoTransfer(source,target,selected,{time,moveStory=false}={}){
  const ids=new Set(selected),chosen=source.photos.filter(p=>ids.has(p.id));
  if(!chosen.length)throw Error('Kies minstens één foto.');
  if(target?.id===source.id)throw Error('Kies een ander verhaal.');
  const destination=target?structuredClone(target):newPhotoStory([],time,source.importBatchId);
  if(target&&time)Object.assign(destination,time);
  const remaining={...source,photos:source.photos.filter(p=>!ids.has(p.id)),currentIndex:0};
  const known=new Set(destination.photos.map(p=>p.fingerprint||p.id));
  destination.photos.push(...chosen.filter(p=>!known.has(p.fingerprint||p.id)));
  if(moveStory){destination.storyText=[destination.storyText,source.storyText].filter(Boolean).join('\n\n');destination.title=destination.title||source.title||'';const recordings=[...new Set([...audioReferences(destination),...audioReferences(source)])];destination.audioId=recordings[0]||'';destination.audioIds=recordings.slice(1);remaining.storyText='';remaining.title='';remaining.audioId='';remaining.audioIds=[];}
  if(!remaining.photos.length&&!remaining.storyText?.trim()&&!audioReferences(remaining).length)remaining.deleted=true;
  return {changes:[remaining,destination],expected:{[source.id]:source.updatedAt,...(target?{[target.id]:target.updatedAt}:{})},destinationId:destination.id};
}

export function createPhotoOrganizer({storage,exclusive,onSaved}){
  installImportStyle();const dialog=document.createElement('dialog');dialog.className='free-import-dialog';dialog.id='freePhotoOrganizer';dialog.innerHTML='<header><button class="close free-close" aria-label="Foto’s indelen sluiten">×</button><h2>Foto’s indelen</h2></header><div class="body"><p>Kies de foto’s voor een apart verhaal of voeg ze bij een bestaand verhaal.</p><div class="tiles"></div><label>Waar horen deze foto’s?<select></select></label><button data-time>Wanneer gebeurde dit?</button><label data-content><input type="checkbox"> Tekst en opnames mee verplaatsen</label><p role="status"></p></div><footer><button data-save class="primary">Bewaren</button></footer>';document.body.append(dialog);
  const grid=dialog.querySelector('.tiles'),select=dialog.querySelector('select'),date=dialog.querySelector('[data-time]'),content=dialog.querySelector('[data-content] input'),status=dialog.querySelector('[role=status]'),save=dialog.querySelector('[data-save]');let source,stories,time,urls=[],busy=false;
  function release(){urls.forEach(URL.revokeObjectURL);urls=[];}function close(){if(busy)return;dialog.close();release();}dialog.querySelector('.close').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});select.onchange=()=>{const target=stories.find(s=>s.id===select.value);const same=target&&timeLabel(target)===timeLabel(source);time=same?{date:target.date,eventTime:target.eventTime}:select.value?null:{date:source.date,eventTime:source.eventTime};date.hidden=Boolean(same);date.textContent=time?timeLabel(time):'Kies de datum of periode van het gecombineerde verhaal';};date.onclick=async()=>{const chosen=await chooseTime(time||{});if(chosen){time=chosen;date.textContent=timeLabel(chosen);}};
  save.onclick=async()=>{if(busy)return;busy=true;save.disabled=true;try{if(!time)throw Error('Kies eerst de datum of periode voor dit verhaal.');const selected=[...grid.querySelectorAll('input:checked')].map(i=>i.value),target=stories.find(s=>s.id===select.value),plan=planPhotoTransfer(source,target,selected,{time,moveStory:content.checked});await exclusive(()=>storage.saveCollection(plan.changes,[],plan.expected));busy=false;close();await onSaved(plan.destinationId);}catch(error){status.textContent=error.name==='QuotaExceededError'?'Onvoldoende ruimte. Je oorspronkelijke verhalen zijn behouden.':error.message;}finally{busy=false;save.disabled=false;}};
  return {async open(id){source=await storage.story(id);if(!source)throw Error('Dit verhaal is niet meer beschikbaar.');stories=(await storage.stories()).filter(s=>s.status==='published'&&s.id!==id);time={date:source.date,eventTime:source.eventTime};release();grid.replaceChildren();select.replaceChildren();const option=document.createElement('option');option.value='';option.textContent='Een apart verhaal';select.append(option);for(const s of stories){const o=document.createElement('option');o.value=s.id;o.textContent=(s.title||timeLabel(s))+' · '+s.photos.length+' foto’s';select.append(o);}date.hidden=false;date.textContent=timeLabel(source);content.checked=false;dialog.querySelector('[data-content]').hidden=!source.storyText?.trim()&&!audioReferences(source).length;status.textContent='';dialog.showModal();for(const p of source.photos){const label=document.createElement('label'),img=document.createElement('img'),check=document.createElement('input');label.className='tile';check.type='checkbox';check.value=p.id;img.alt=p.name||'Foto';label.append(img,check);grid.append(label);const m=await storage.media(p.id);if(m){const url=URL.createObjectURL(m.thumbnail||m.blob);urls.push(url);img.src=url;}}}};
}
