import {chooseTime,installDateStyle} from './date-picker.js';
import {timeLabel} from './dates.browser.js';
export function installOverview({getStory,save,media,storage,notice}){
  installDateStyle();const dialog=document.createElement('dialog');dialog.id='freeOverview';dialog.innerHTML='<header><button class="free-close" type="button" aria-label="Bewerken sluiten">×</button><h2>Verhaal bewerken</h2></header><label>Titel<input id="freeOverviewTitle"></label><button type="button" id="freeOverviewDate"></button><h3>Foto’s en video’s</h3><div id="freeOverviewMedia"></div><label>Je verhaal<textarea id="freeOverviewText" rows="6"></textarea></label><audio controls hidden></audio><button type="button" id="freeOverviewSpeak">Verder vertellen</button><p role="status"></p><button type="button" id="freeOverviewSave">Bewaar en bekijk je verhaal</button>';
  const style=document.createElement('style');style.textContent='#freeOverview header{display:flex;align-items:center;justify-content:space-between;flex-direction:row-reverse}#freeOverview h2{font-size:23px;margin:0 0 16px}#freeOverview h3{font-size:17px;margin:16px 0 8px}#freeOverviewMedia .photo-manage-grid{display:flex;gap:8px;overflow-x:auto;max-height:126px;padding:4px 0 10px}#freeOverviewMedia .photo-manage-tile{flex:0 0 98px;width:98px;height:98px;aspect-ratio:1}#freeOverviewMedia img{width:100%;height:100%;object-fit:cover}#freeOverview textarea{min-height:130px}#freeOverviewSave{background:#173851!important;color:white!important;width:100%;margin-top:12px}#freeOverviewDate{margin-top:10px}';document.head.append(style);
  document.body.append(dialog);const title=dialog.querySelector('input'),text=dialog.querySelector('textarea'),date=dialog.querySelector('#freeOverviewDate'),audio=dialog.querySelector('audio');let time={},audioUrl='',changed=false;
  const sync=()=>{document.getElementById('title').value=title.value;document.getElementById('storyText').value=text.value;document.getElementById('storyText').dispatchEvent(new Event('input',{bubbles:true}));changed=true;};title.oninput=text.oninput=sync;
  const saveChanges=async()=>{if(!changed)return;await save({title:title.value,titleSource:title.value!==getStory().title?'manual':getStory().titleSource,storyText:text.value,...time});changed=false;};
  date.onclick=async()=>{const result=await chooseTime(time);if(result){time=result;date.textContent=timeLabel(time);changed=true;}};
  async function open(){const story=getStory();title.value=story.title||'';text.value=story.storyText||'';time={date:story.date,eventTime:story.eventTime,datePrecision:story.datePrecision};date.textContent=timeLabel(story);changed=false;dialog.querySelector('#freeOverviewMedia').append(document.getElementById('photoManageGrid'));await media.renderManager();if(audioUrl)URL.revokeObjectURL(audioUrl);audio.hidden=!story.audioId;if(story.audioId){const item=await storage.media(story.audioId);if(item){audioUrl=URL.createObjectURL(item.blob);audio.src=audioUrl;}}dialog.showModal();}
  const close=async()=>{try{await saveChanges();audio.pause();dialog.close();}catch(e){notice(e.message);}};dialog.querySelector('header button').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.querySelector('#freeOverviewSpeak').onclick=async()=>{await close();document.getElementById('screen').dataset.freeStep='story';window.__taleraFreeOpenText?.();};dialog.querySelector('#freeOverviewSave').onclick=async()=>{try{await saveChanges();document.getElementById('timelinePublish').click();}catch(e){notice(e.message);}};
  if(getStory().status==='published'){document.getElementById('editBtn').addEventListener('click',e=>{e.stopImmediatePropagation();open().catch(e=>notice(e.message));},true);document.getElementById('managePhotosBtn').onclick=()=>open().catch(e=>notice(e.message));open().catch(e=>notice(e.message));}
  return {open};
}
