export function resample(samples,rate){const ratio=rate/16000,result=new Float32Array(Math.floor(samples.length/ratio));for(let i=0;i<result.length;i++){const start=Math.floor(i*ratio),end=Math.min(samples.length,Math.floor((i+1)*ratio));let sum=0;for(let j=start;j<end;j++)sum+=samples[j];result[i]=sum/Math.max(1,end-start);}return result;}
export function createSpeech({onText,onStatus,onError}){
  let worker,context,node,source,pending=[],busy=false,ready=false,paused=false,stopping=false,nextId=0;
  function pump(){if(!ready||busy||!pending.length)return;busy=true;const samples=pending.shift();worker.postMessage({kind:'transcribe',id:++nextId,samples},[samples.buffer]);}
  function prepare(){if(worker)return;onStatus('Spraak voorbereiden · eenmalige modeldownload. Je stem blijft op dit toestel.');worker=new Worker('/local/speech-worker.js',{type:'module'});worker.onerror=event=>{console.error('TALERA speech worker:',event.message,event.filename);onError('Spraakmodel kon niet worden geladen. Je opname blijft bewaard.');ready=false;busy=false;pending=[];worker.terminate();worker=null;};worker.onmessage=({data})=>{if(data.kind==='ready'){ready=true;onStatus('Je woorden verschijnen met een korte vertraging.');pump();}else if(data.kind==='text'){busy=false;if(data.text.trim())onText(data.text.trim());pump();if(stopping&&!busy&&!pending.length)onStatus('Tekst bewaard.');}else if(data.kind==='error'){console.error('TALERA speech model:',data.message);busy=false;onError('Tekst omzetten lukte niet. Je opname blijft bewaard.');pending=[];ready=false;worker.terminate();worker=null;}else if(data.kind==='progress'&&Number.isFinite(data.progress))onStatus('Spraakmodel downloaden · '+Math.round(data.progress)+'%');};worker.postMessage({kind:'prepare'});}
  async function start(stream){prepare();paused=false;stopping=false;context=new (globalThis.AudioContext||globalThis.webkitAudioContext)();await context.audioWorklet.addModule('/local/speech-worklet.js');if(stopping){await context.close();context=null;return;}await context.resume();node=new AudioWorkletNode(context,'talera-samples');source=context.createMediaStreamSource(stream);node.port.onmessage=({data})=>{if(paused)return;const samples=resample(data.samples,data.rate);const rms=Math.sqrt(samples.reduce((sum,v)=>sum+v*v,0)/samples.length);if(rms<.003)return;if(pending.length>=10){onError('Tekst omzetten loopt achter. Je volledige opname blijft bewaard.');return;}pending.push(samples);pump();};source.connect(node);const silence=context.createGain();silence.gain.value=0;node.connect(silence).connect(context.destination);}
  function stop(){stopping=true;node?.port.postMessage('flush');source?.disconnect();setTimeout(()=>{context?.close().catch(()=>{});context=null;},100);}
  async function transcribeBlob(blob){prepare();const audioContext=new (globalThis.AudioContext||globalThis.webkitAudioContext)();try{const buffer=await audioContext.decodeAudioData(await blob.arrayBuffer());const samples=resample(buffer.getChannelData(0),buffer.sampleRate);for(let at=0;at<samples.length;at+=16000*20)pending.push(samples.slice(at,at+16000*20));stopping=true;pump();}finally{await audioContext.close();}}
  return {transcribeBlob,start,stop,pause:()=>{node?.port.postMessage('flush');paused=true;},resume:()=>paused=false,busy:()=>busy||pending.length>0,dispose:()=>{stop();worker?.terminate();}};
}
