import {chooseTime,checkedTime,installDateStyle} from './date-picker.js';
import {timeLabel} from './dates.browser.js';
import {importPhotos} from './photos.js';
import {createRecorder} from './recorder.js';
import {createSpeech} from './speech.browser.js';

// Editing has its own in-memory draft. Nothing replaces the saved story before Save.
export function createStoryEditor({storage,exclusive,onSaved,importMedia=importPhotos,recorderFactory=createRecorder,speechFactory=createSpeech}){
  installDateStyle();
  const dialog=document.createElement('dialog');dialog.id='freeStoryEditor';dialog.setAttribute('aria-labelledby','freeStoryEditorHeading');
  dialog.innerHTML=`<header><button class="free-close" type="button" aria-label="Bewerken sluiten">×</button><h2 id="freeStoryEditorHeading">Verhaal bewerken</h2></header>
    <div class="free-editor-body"><section aria-label="Foto’s en video’s"><h3>Foto’s en video’s</h3><div id="freeEditorPhotos"></div><input id="freeEditorFiles" type="file" accept="image/*,video/*" multiple hidden></section>
    <label for="freeEditorText">Je verhaal</label><textarea id="freeEditorText" rows="6" placeholder="Wat gebeurde er?"></textarea>
    <div class="free-editor-voice"><button type="button" id="freeEditorRecord">🎙 Tekst inspreken</button><button type="button" id="freeEditorPause" hidden>Pauze</button><button type="button" id="freeEditorStop" hidden>Stop opname</button></div>
    <audio id="freeEditorAudio" controls preload="metadata" hidden></audio><button type="button" id="freeEditorRemoveAudio" hidden>Opname verwijderen</button>
    <label for="freeEditorTitle">Titel</label><input id="freeEditorTitle" maxlength="140"><h3>Wanneer gebeurde dit verhaal?</h3><button type="button" id="freeEditorDate"></button>
    <p id="freeEditorStatus" role="status" aria-live="polite"></p></div><footer><button type="button" id="freeEditorSave">Opslaan en sluiten</button></footer>`;
  const style=document.createElement('style');style.textContent=`#freeStoryEditor{position:fixed;inset:8px;margin:auto;width:calc(100% - 16px);max-width:760px;height:calc(100dvh - 16px);max-height:calc(100dvh - 16px);padding:0;box-sizing:border-box;border:1px solid #cad6df;border-radius:24px;background:#fff;color:#173851;font:16px/1.5 system-ui;box-shadow:0 20px 70px #0005;overflow:hidden}#freeStoryEditor[open]{display:flex;flex-direction:column}#freeStoryEditor::backdrop{background:#071b2e66}#freeStoryEditor header{display:flex;align-items:center;justify-content:space-between;flex-direction:row-reverse;padding:14px 20px;border-bottom:1px solid #e2e8ed;background:#fff;flex-shrink:0}#freeStoryEditor h2{font-size:22px;margin:0}#freeStoryEditor h3{font-size:16px;margin:12px 0 8px}#freeStoryEditor header .free-close{float:none;position:static;margin:0!important}#freeStoryEditor .free-editor-body{padding:8px 20px 18px;overflow:auto;overscroll-behavior:contain;flex:1;min-height:0}#freeStoryEditor label{display:block;font-weight:600;margin:14px 0 6px}#freeStoryEditor input:not([type=file]),#freeStoryEditor textarea{width:100%;box-sizing:border-box;background:#fff;color:#173851;font:inherit;padding:12px;border:1px solid #cbd5dd;border-radius:12px}#freeEditorText{min-height:145px;resize:vertical}#freeStoryEditor button{font:inherit;cursor:pointer;border:0;border-radius:14px;padding:11px 14px;background:#e8eef2;color:#173851}#freeStoryEditor button:disabled{opacity:.5;cursor:wait}#freeStoryEditor [hidden]{display:none!important}#freeEditorPhotos{display:flex;gap:10px;overflow-x:auto;padding:4px 0 8px;min-height:100px}#freeEditorPhotos .free-editor-tile{position:relative;flex:0 0 96px;width:96px;height:96px;box-sizing:border-box;border:1px solid #d5e0e7;border-radius:14px;overflow:hidden;background:#e8eef2}#freeEditorPhotos img{width:100%;height:100%;object-fit:cover}#freeEditorPhotos .free-editor-remove{position:absolute;right:3px;top:3px;padding:0;width:29px;height:29px;border-radius:50%;background:white;color:#173851;font-size:23px}#freeEditorPhotos .free-editor-add{font-size:30px}#freeEditorPhotos .free-editor-video{position:absolute;bottom:4px;left:7px;color:white;background:#173851bb;padding:1px 6px;border-radius:10px}#freeStoryEditor .free-editor-voice{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}#freeStoryEditor audio{width:100%;height:38px;margin:8px 0}#freeStoryEditor footer{padding:12px 20px calc(12px + env(safe-area-inset-bottom));border-top:1px solid #e2e8ed;flex-shrink:0;background:#fff}#freeEditorSave{width:100%;background:#173851!important;color:white!important;font-weight:700!important}#freeEditorStatus{font-size:14px;min-height:20px;margin:10px 0 0}#freeEditorRecord[aria-pressed=true]{background:#a54646;color:white}`;document.head.append(style);document.body.append(dialog);
  const title=dialog.querySelector('#freeEditorTitle'),text=dialog.querySelector('#freeEditorText'),grid=dialog.querySelector('#freeEditorPhotos'),files=dialog.querySelector('#freeEditorFiles'),date=dialog.querySelector('#freeEditorDate'),audio=dialog.querySelector('audio'),status=dialog.querySelector('[role=status]'),saveButton=dialog.querySelector('#freeEditorSave'),recordButton=dialog.querySelector('#freeEditorRecord'),pauseButton=dialog.querySelector('#freeEditorPause'),stopButton=dialog.querySelector('#freeEditorStop'),removeAudio=dialog.querySelector('#freeEditorRemoveAudio');
  let original=null,draft=null,pending=new Map(),urls=[],audioUrl='',renderToken=0,session=0,importing=false,saving=false,opening=false,dirty=false,recorder=null,speech=null,phase='idle',closePrompt=null;
  function busy(){return importing||saving||recorder?.busy()||speech?.busy();}
  function mark(){dirty=true;}
  function controls(){const recording=['permission','recording','paused','saving'].includes(phase);saveButton.disabled=Boolean(busy());recordButton.disabled=recording||Boolean(speech?.busy())||importing;recordButton.setAttribute('aria-pressed',String(recording));pauseButton.hidden=!['recording','paused'].includes(phase);pauseButton.textContent=phase==='paused'?'Verder inspreken':'Pauze';stopButton.hidden=!['recording','paused'].includes(phase);}
  const getMedia=id=>pending.has(id)?Promise.resolve(pending.get(id)):storage.media(id);
  async function render(){const token=++renderToken;urls.forEach(URL.revokeObjectURL);urls=[];grid.replaceChildren();const add=document.createElement('button');add.type='button';add.className='free-editor-tile free-editor-add';add.textContent='+';add.setAttribute('aria-label','Foto of video toevoegen');add.disabled=importing||saving;add.onclick=()=>files.click();grid.append(add);
    for(const entry of draft.photos){const tile=document.createElement('div');tile.className='free-editor-tile';const img=document.createElement('img');img.alt=entry.name||'Foto';const del=document.createElement('button');del.type='button';del.className='free-editor-remove';del.textContent='×';del.setAttribute('aria-label',(entry.name||'Foto')+' verwijderen');del.disabled=importing||saving;del.onclick=()=>{draft.photos=draft.photos.filter(p=>p.id!==entry.id);pending.delete(entry.id);mark();render().catch(error=>status.textContent=error.message);};tile.append(img,del);if(entry.kind==='video'){const indicator=document.createElement('span');indicator.className='free-editor-video';indicator.textContent='▶';tile.append(indicator);}grid.append(tile);const media=await getMedia(entry.id);if(token!==renderToken||!dialog.open)return;if(media){const url=URL.createObjectURL(media.thumbnail||media.blob);urls.push(url);img.src=url;}}
  }
  async function loadAudio(){if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl='';audio.pause();audio.removeAttribute('src');const media=draft.audioId?await getMedia(draft.audioId):null;audio.hidden=removeAudio.hidden=!media;if(media){audioUrl=URL.createObjectURL(media.blob);audio.src=audioUrl;}}
  function release(){renderToken++;urls.forEach(URL.revokeObjectURL);urls=[];audio.pause();audio.removeAttribute('src');if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl='';speech?.dispose();speech=null;recorder=null;phase='idle';pending.clear();closePrompt?.remove();closePrompt=null;}
  function finish(){dialog.close();session++;release();window.dispatchEvent(new Event('talera-editor-close'));}
  async function save(){if(busy()){status.textContent='Rond eerst je opname of het toevoegen van foto’s af.';return;}saving=true;controls();status.textContent='Je wijzigingen bewaren…';try{const time=checkedTime({date:draft.date,eventTime:draft.eventTime});const value={...draft,...time,title:title.value.trim(),titleSource:title.value.trim()!==original.title?'manual':original.titleSource,storyText:text.value,currentIndex:Math.min(draft.currentIndex||0,Math.max(0,draft.photos.length-1))};if(!value.title)throw Error('Vul een titel in.');if(!value.photos.length&&!value.storyText.trim()&&!value.audioId)throw Error('Bewaar minstens een foto of verhaal.');if(value.storyText!==original.storyText)delete value.analysis;const ids=new Set([...value.photos.map(p=>p.id),value.audioId].filter(Boolean));const saved=await exclusive(()=>storage.saveEdit(value,[...pending.values()].filter(m=>ids.has(m.id)),original.updatedAt));dirty=false;await onSaved(saved);finish();}catch(error){status.textContent=error.name==='QuotaExceededError'?'Je toestel heeft onvoldoende ruimte. Je wijzigingen staan nog in dit venster.':error.message;}finally{saving=false;controls();}}
  function requestClose(){if(busy()){status.textContent='Stop eerst je opname en wacht totdat je woorden verwerkt zijn.';return;}if(!dirty){finish();return;}if(closePrompt?.open)return;closePrompt=document.createElement('dialog');closePrompt.className='free-time-dialog';closePrompt.innerHTML='<h2>Wijzigingen bewaren?</h2><p>Je hebt dit verhaal aangepast.</p><button data-save>Opslaan en sluiten</button><button data-discard>Wijzigingen niet bewaren</button><button data-back>Verder bewerken</button>';document.body.append(closePrompt);closePrompt.querySelector('[data-save]').onclick=()=>{closePrompt.remove();closePrompt=null;save();};closePrompt.querySelector('[data-discard]').onclick=finish;closePrompt.querySelector('[data-back]').onclick=()=>{closePrompt.remove();closePrompt=null;};closePrompt.addEventListener('cancel',e=>{e.preventDefault();closePrompt.remove();closePrompt=null;});closePrompt.showModal();}
  title.oninput=text.oninput=mark;date.onclick=async()=>{if(busy())return;const result=await chooseTime(draft);if(result){Object.assign(draft,result);date.textContent=timeLabel(draft);mark();}};
  files.onchange=async()=>{const chosen=Array.from(files.files||[]);files.value='';if(!chosen.length||busy())return;importing=true;mark();controls();await render();try{await importMedia(chosen,{getStory:()=>draft,preview:()=>{},commit:async(media,entry)=>{pending.set(media.id,media);draft.photos.push(entry);await render();},progress:(done,duplicates,failed,total,error)=>status.textContent=error||`${done} / ${total} toegevoegd${duplicates?' · '+duplicates+' al aanwezig':''}`,onDuplicate:async()=>{}});}catch(error){status.textContent=error.message;}finally{importing=false;controls();await render();}};
  recordButton.onclick=async()=>{if(busy())return;if(draft.audioId){status.textContent='Een nieuwe opname vervangt je huidige opname pas nadat je opslaat.';}audio.pause();try{await recorder.start();}catch(error){status.textContent=error.message;controls();}};pauseButton.onclick=()=>phase==='paused'?recorder.resume():recorder.pause();stopButton.onclick=()=>recorder.stop();removeAudio.onclick=()=>{if(busy())return;pending.delete(draft.audioId);draft.audioId='';mark();loadAudio();};saveButton.onclick=save;dialog.querySelector('header button').onclick=requestClose;dialog.addEventListener('cancel',e=>{e.preventDefault();requestClose();});
  async function open(id,{focusPhotos=false}={}){if(dialog.open||opening)return;opening=true;try{original=await storage.story(id);if(!original)throw Error('Dit verhaal is niet meer beschikbaar.');draft=structuredClone(original);pending=new Map();dirty=false;title.value=draft.title||'';text.value=draft.storyText||'';date.textContent=timeLabel(draft);status.textContent='';phase='idle';const token=++session;
    speech=speechFactory({onText:value=>{if(token!==session)return;text.value+=(text.value.trim()?' ':'')+value;mark();controls();},onStatus:value=>{if(token!==session)return;status.textContent=value;controls();},onError:value=>{if(token!==session)return;status.textContent=value;controls();}});
    recorder=recorderFactory({save:async media=>{if(token!==session)return;pending.set(media.id,media);draft.audioId=media.id;mark();if(!media.incomplete)await loadAudio();},onStream:stream=>speech.start(stream).catch(()=>status.textContent='Tekst omzetten lukt niet. Je opname kun je wel bewaren.'),onError:error=>{status.textContent=error.message;controls();},onState:value=>{phase=value;if(value==='saving')speech.stop();if(value==='paused')speech.pause();if(value==='recording')speech.resume();status.textContent={permission:'Microfoon toestaan…',recording:'Je spreekt in. Je woorden verschijnen hieronder.',paused:'Opname gepauzeerd.',saving:'Opname verwerken…',saved:'Opname gereed. Kies Opslaan en sluiten.'}[value]||'';controls();}});
    dialog.showModal();window.dispatchEvent(new Event('talera-editor-open'));await render();await loadAudio();controls();if(focusPhotos)grid.querySelector('button')?.focus();
  }finally{opening=false;}}
  window.addEventListener('beforeunload',e=>{if(dialog.open&&(dirty||busy())){e.preventDefault();e.returnValue='';}});document.addEventListener('visibilitychange',()=>{if(document.hidden)recorder?.stop(true);});window.addEventListener('pagehide',()=>{recorder?.stop(true);if(!recorder?.busy())release();});
  return {open,busy:()=>Boolean(dialog.open&&(dirty||busy()))};
}
