import {videoNarration} from './video.js';
export function installTellMedia({getStory,storage,remove,notice}){
  const screen=document.getElementById('screen'),stage=document.createElement('div');stage.id='freeMediaStage';stage.innerHTML='<img alt="Foto bij je herinnering"><video playsinline preload="metadata"></video>';
  const play=document.createElement('button');play.id='freeVideoPlay';play.type='button';play.textContent='▶';play.setAttribute('aria-label','Video afspelen');play.hidden=true;screen.prepend(stage);screen.append(play);
  const image=stage.querySelector('img'),video=stage.querySelector('video'),modal=document.getElementById('photoManageModal'),grid=document.getElementById('photoManageGrid'),input=document.getElementById('photoInput');input.accept='image/*,video/*';
  const style=document.createElement('style');style.textContent='#screen #bgPhoto,.talera-story-carousel,.talera-story-dots{display:none!important}#freeMediaStage{position:absolute;inset:0;z-index:0;pointer-events:none}#freeMediaStage img,#freeMediaStage video{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}#freeMediaStage [hidden]{display:none}#freeVideoPlay{position:absolute;z-index:9;left:50%;top:46%;transform:translate(-50%,-50%);width:58px;height:58px;border-radius:50%;background:#173851d9;color:white;border:1px solid white;font-size:25px}#freeVideoPlay[hidden]{display:none}.free-media-mark{position:absolute;left:8px;bottom:8px;color:white;background:#173851b8;border-radius:50%;padding:5px}.photo-manage-grid{max-height:55dvh;overflow:auto}.photo-manage-tile{position:relative}';document.head.append(style);
  document.getElementById('managePhotosBtn').querySelector('span').textContent='Foto’s en video’s beheren';modal.querySelector('h3').textContent='Foto’s en video’s beheren';
  let managerGeneration=0,index=0,key='',urls=[],thumbs=[],generation=0,deadline=Date.now()+2000,link=null,wasBlocked=false;
  const blocked=()=>document.hidden||Boolean(document.querySelector('.modal.open,dialog[open]'))||screen.classList.contains('sheet-open');
  function clear(){link?.release();link=null;video.pause();video.removeAttribute('src');video.load();urls.forEach(URL.revokeObjectURL);urls=[];}
  async function show(){const story=getStory();if(!story.photos.length){key='';generation++;clear();stage.hidden=true;play.hidden=true;return;}index%=story.photos.length;const entry=story.photos[index],next=entry.id+':'+(story.fit||'cover');if(key===next)return;key=next;const token=++generation;clear();play.hidden=true;stage.hidden=false;const item=await storage.media(entry.id);if(token!==generation||!item)return;image.style.objectFit=video.style.objectFit=story.fit==='contain'?'contain':'cover';const url=URL.createObjectURL(item.kind==='video'?item.thumbnail:item.blob);urls.push(url);image.src=url;image.hidden=false;video.hidden=true;deadline=Date.now()+2000;
    if(item.kind==='video'){const source=URL.createObjectURL(item.blob);urls.push(source);video.poster=url;video.src=source;video.hidden=false;video.muted=Boolean(window.__taleraFreeRecording?.busy());link=videoNarration(video,document.getElementById('freeAudioPlayer'),()=>!blocked());play.hidden=false;if(!blocked())startVideo();}
  }
  async function startVideo(){video.muted=Boolean(window.__taleraFreeRecording?.busy());try{await video.play();play.hidden=true;}catch{play.hidden=false;}}
  play.onclick=startVideo;
  video.onended=()=>{if(getStory().photos.length>1){index=(index+1)%getStory().photos.length;show().catch(e=>notice(e.message));}else play.hidden=false;};
  const tick=()=>{const nowBlocked=blocked();if(nowBlocked){if(!video.paused)video.pause();wasBlocked=true;deadline=Date.now()+2000;return;}if(wasBlocked){wasBlocked=false;deadline=Date.now()+2000;if(video.src&&!video.ended)startVideo();}video.muted=Boolean(window.__taleraFreeRecording?.busy());if(!video.src&&getStory().photos.length>1&&Date.now()>=deadline){index=(index+1)%getStory().photos.length;show().catch(e=>notice(e.message));}};
  const timer=setInterval(tick,100);
  async function manager(){const token=++managerGeneration;thumbs.forEach(URL.revokeObjectURL);thumbs=[];grid.replaceChildren();const photos=getStory().photos.slice();document.getElementById('photoManageCount').textContent=photos.length+' items';const add=document.createElement('button');add.type='button';add.className='photo-manage-tile photo-manage-add';add.textContent='+';add.setAttribute('aria-label','Foto of video toevoegen');add.onclick=()=>input.click();grid.append(add);
    for(const entry of photos){const tile=document.createElement('div');tile.className='photo-manage-tile';const img=document.createElement('img');img.alt=entry.name;const del=document.createElement('button');del.type='button';del.className='photo-manage-remove';del.textContent='×';del.setAttribute('aria-label',entry.name+' verwijderen');del.onclick=async()=>{del.disabled=true;try{await remove(entry.id);index=0;key='';await show();await manager();}catch(e){notice(e.message);del.disabled=false;}};tile.append(img,del);if(entry.kind==='video'){const mark=document.createElement('span');mark.className='free-media-mark';mark.textContent='▶';tile.append(mark);}grid.append(tile);const item=await storage.media(entry.id);if(token!==managerGeneration)return;if(item){const url=URL.createObjectURL(item.thumbnail);thumbs.push(url);img.src=url;}}
  }
  document.getElementById('managePhotosBtn').onclick=()=>{document.getElementById('moreModal').classList.remove('open');modal.classList.add('open');manager().catch(e=>notice(e.message));};
  function refresh(){const photos=getStory().photos;if(!photos.some(p=>key.startsWith(p.id+':')))index=Math.min(getStory().currentIndex||0,Math.max(0,photos.length-1));show().catch(e=>notice(e.message));if(modal.classList.contains('open'))manager().catch(e=>notice(e.message));}
  window.addEventListener('talera-free-saved',refresh);window.addEventListener('talera-guided-ready',refresh);window.addEventListener('pagehide',()=>{clearInterval(timer);generation++;clear();thumbs.forEach(URL.revokeObjectURL);});refresh();
}
