import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {JSDOM}=await import(process.env.FREE_JSDOM_MODULE||'jsdom');
const dom=new JSDOM('<main id="screen"><header class="top"><input id="title"><label class="date"></label></header><textarea id="storyText"></textarea><button id="timelinePublish"></button><input id="editTitle"><input id="editDate"><button id="editBtn"></button></main>',{pretendToBeVisual:true});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,localStorage:{getItem:()=>null,setItem:()=>{}}});
let resolveTitle,saves=0;globalThis.createTitle=()=>({suggest:()=>new Promise(resolve=>resolveTitle=resolve)});
let draft={photos:[],storyText:'',title:'',status:'draft'};
const code=(await readFile(new URL('./guided.browser.js',import.meta.url),'utf8')).replace(/^import .*;\n/,'');
const {installGuidedTell}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
installGuidedTell({getStory:()=>draft,flush:async()=>{},saveTitle:async(title,current)=>{if(!current())return false;saves++;draft.title=title;draft.titleSource='ai';return true;},notice:()=>{}});
assert.equal(document.getElementById('title').hidden,true);assert.equal(document.querySelector('.date').hidden,true);assert.equal(document.getElementById('timelinePublish').hidden,true);
document.getElementById('freeSkipPhoto').click();assert.equal(document.getElementById('screen').dataset.freeStep,'story');
const field=document.getElementById('storyText');field.value='Een wandeling door het bos.';field.dispatchEvent(new window.Event('input'));assert.equal(document.getElementById('freeReview').hidden,false);
document.getElementById('freeReview').click();await new Promise(r=>setTimeout(r,0));assert.equal(document.getElementById('title').hidden,false);assert.equal(document.getElementById('editTitle').value,'Een wandeling door het bos');document.getElementById('freeTitleRetry').click();
const edit=document.getElementById('editTitle');edit.value='Mijn eigen titel';edit.dispatchEvent(new window.Event('input'));resolveTitle('Wandeling door het bos');await new Promise(r=>setTimeout(r,0));assert.equal(edit.value,'Mijn eigen titel');assert.equal(saves,1);
dom.window.close();
console.log('Guided flow: photo optional, fields deferred, review available, late AI never overwrites manual title.');
