import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import 'fake-indexeddb/auto';
import {storage} from './storage.browser.js';
import {createBackup,readBackup} from './backup.browser.js';
const dateSource=(await readFile(new URL('./date-picker.browser.js',import.meta.url),'utf8')).replace("'./dates.browser.js'",JSON.stringify(new URL('./dates.browser.js',import.meta.url).href));
const data=source=>'data:text/javascript;base64,'+Buffer.from(source).toString('base64');
let source=await readFile(new URL('./bulk.browser.js',import.meta.url),'utf8');source=source.replace(/^import \{photoFingerprint,photoDate\}.*;\n/gm,'const photoFingerprint=()=>{},photoDate=()=>{};\n').replace(/^import \{compactPhoto\}.*;\n/gm,'const compactPhoto=()=>{};\n').replace("'./date-picker.js'",JSON.stringify(data(dateSource))).replace("'./dates.browser.js'",JSON.stringify(new URL('./dates.browser.js',import.meta.url).href));
const bulkURL=data(source),{prepareBatch,buildBatch,batchGroups}=await import(bulkURL);
let organize=await readFile(new URL('./organizer.browser.js',import.meta.url),'utf8');organize=organize.replace("'./bulk.js'",JSON.stringify(bulkURL)).replace("'./date-picker.js'",JSON.stringify(data(dateSource))).replace("'./dates.browser.js'",JSON.stringify(new URL('./dates.browser.js',import.meta.url).href));const {planPhotoTransfer}=await import(data(organize));
const photo=name=>new File([name],name+'.jpg',{type:'image/jpeg'});
const compact=async file=>({id:crypto.randomUUID(),kind:'photo',blob:new Blob([file.name],{type:'image/jpeg'}),thumbnail:new Blob(['thumb'],{type:'image/jpeg'})});
const batch=await prepareBatch([photo('a'),photo('a'),photo('b'),photo('unknown')],[],{compact,fingerprint:async f=>f.name,capture:async f=>f.name==='unknown.jpg'?'':'2020-05-01'});
assert.equal(batch.duplicates,1);assert.equal(batch.entries.length,3);assert.equal(batchGroups(batch.entries).length,1);assert.throws(()=>buildBatch(batch,[]),/iedere foto/);
batch.entries[2].time={eventTime:{kind:'year',year:2019},date:''};const plan=buildBatch(batch,[]);assert.equal(plan.changes.length,2);assert.ok(plan.changes.every(s=>s.title===''&&s.storyText===''));await storage.saveCollection(plan.changes,plan.media,plan.expected,plan.summary);
assert.equal((await storage.lastImport()).groups.length,2);const backup=await readBackup((await createBackup(storage)).file);assert.equal(backup.imports.length,1);assert.equal(backup.stories.find(s=>s.eventTime)?.eventTime.kind,'year');
const from=await storage.story(plan.changes[0].id),to=await storage.story(plan.changes[1].id);from.storyText='Verhaal blijft behouden';from.audioId='voice';await storage.commitMedia(from,{id:'voice',kind:'audio',blob:new Blob(['voice'],{type:'audio/mp4'})});const original=await storage.story(from.id);
const moved=planPhotoTransfer(original,to,original.photos.map(p=>p.id),{time:{eventTime:{kind:'year',year:2020},date:''},moveStory:true});await storage.saveCollection(moved.changes,[],moved.expected);assert.equal(await storage.story(from.id),undefined);assert.equal((await storage.story(to.id)).photos.length,3);assert.ok(await storage.media('voice'));assert.match((await storage.story(to.id)).storyText,/behouden/);
await assert.rejects(storage.saveCollection([{...to,title:'stale'}],[],{[to.id]:to.updatedAt}),/ondertussen/);assert.equal((await storage.story(to.id)).photos.length,3);
const before=await storage.story(to.id);await assert.rejects(storage.saveCollection([{...before,photos:[{id:'missing'}]}],[],{[to.id]:before.updatedAt}));assert.equal((await storage.story(to.id)).photos.length,3);
const roundtrip=await readBackup((await createBackup(storage)).file);assert.ok(roundtrip.stories[0].audioId);assert.equal(roundtrip.stories[0].eventTime.kind,'year');await storage.restore(roundtrip);assert.ok(await storage.media('voice'));
await assert.rejects(prepareBatch(Array.from({length:26},()=>photo('z')),[]),/25/);
console.log('Bulk deduplication, dates, backup, atomic transfer, speech preservation and conflicts passed.');
