const {JSDOM,VirtualConsole}=await import(process.env.FREE_JSDOM_MODULE||'jsdom');
await import(process.env.FREE_INDEXEDDB_MODULE||'fake-indexeddb/auto');
import {storage} from './storage.browser.js';
import {makePages} from './pages.js';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
await storage.putMedia({id:'dom-photo',blob:new Blob(['photo']),thumbnail:new Blob(['thumb'])});
await storage.save({id:'dom-story',photos:[{id:'dom-photo'}],title:'Lokale proef',date:'2021-04-10',storyText:'De tekst blijft hier.',status:'published'});
const errors=[];const console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM((await makePages()).timeline,{url:'http://localhost/#story=dom-story',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:console});
const w=dom.window;w.__testStorage=storage;w.__copy=(await import('./copy.browser.js')).t;w.Blob=Blob;w.Response=Response;w.URL=URL;
w.requestAnimationFrame=()=>1;w.ResizeObserver=class{observe(){}disconnect(){}};
w.HTMLCanvasElement.prototype.getContext=function(){return new Proxy({measureText:t=>({width:String(t).length*6}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)});};
w.HTMLElement.prototype.getBoundingClientRect=function(){return {width:390,height:212,left:0,top:0,right:390,bottom:212};};
const bridge=(await readFile(new URL('./bridge.browser.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');
await w.eval('(async()=>{const storage=window.__testStorage;const compactPhoto=()=>{};const t=window.__copy;const installBackup=()=>{};const installDeviceExperience=()=>{};const installTellExperience=()=>{};const installTimelineExperience=()=>{};const importPhotos=()=>{};'+bridge+'})()');
assert.equal(w.__taleraTimelineRuntime.currentMemory().storyId,'dom-story');
assert.equal(w.document.getElementById('memoryStory').textContent,'Lokale proef');
assert.equal(w.document.getElementById('memoryStoryMore').textContent,'De tekst blijft hier.');
assert.ok(Number.isFinite(w.__taleraTimelineRuntime.centerMs()));
assert.deepEqual(errors,[]);
dom.window.close();
const tellErrors=[];const tellConsole=new VirtualConsole();tellConsole.on('jsdomError',e=>tellErrors.push(e.message));
const tellDom=new JSDOM((await makePages()).tell,{url:'http://localhost/tell#edit=dom-story',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:tellConsole});
const tw=tellDom.window;tw.__testStorage=storage;tw.__copy=(await import('./copy.browser.js')).t;tw.Blob=Blob;tw.Response=Response;tw.URL=URL;tw.requestAnimationFrame=()=>1;tw.ResizeObserver=class{observe(){}disconnect(){}};
await tw.eval('(async()=>{const storage=window.__testStorage;const compactPhoto=()=>{};const t=window.__copy;const installBackup=()=>{};const installDeviceExperience=()=>{};const installTellExperience=()=>{};const installTimelineExperience=()=>{};const importPhotos=()=>{};'+bridge+'})()');
await new Promise(resolve=>setTimeout(resolve,100));
assert.equal(tw.document.getElementById('title').value,'Lokale proef');
assert.equal(tw.document.getElementById('dateInput').value,'2021-04-10');
assert.equal(tw.document.getElementById('storyText').value,'De tekst blijft hier.');
// Drag to a middle position, release, then resize: no snap to open/closed.
const panel=tw.document.getElementById('sheet');
function touch(type,y){
  const event=new tw.Event(type,{bubbles:true,cancelable:true});
  Object.defineProperty(event,'touches',{value:type==='touchend'?[]:[{clientY:y}]});
  Object.defineProperty(event,'changedTouches',{value:[{clientY:y}]});
  panel.dispatchEvent(event);
}
const originalOffset=Number(panel.style.transform.match(/,([\d.]+)px/)[1]);
touch('touchstart',600);touch('touchmove',400);touch('touchend',400);
const heldOffset=Number(panel.style.transform.match(/,([\d.]+)px/)[1]);
assert.ok(Math.abs(heldOffset-(originalOffset-200))<1);
tw.dispatchEvent(new tw.Event('resize'));
assert.equal(Number(panel.style.transform.match(/,([\d.]+)px/)[1]),heldOffset);
tw.document.getElementById('storyText').value='De tekst blijft hier.';
tw.document.getElementById('storyText').dispatchEvent(new tw.Event('input'));
assert.equal(tw.document.getElementById('sheetPreview').textContent,'De tekst blijft hier.');
tw.document.getElementById('sheetClose').click();
// A photo-only draft must expose the next step instead of hiding publication.
assert.ok((await makePages()).tell.includes('.screen.has-photo .talera-publish-timeline{display:flex}'));
tw.document.getElementById('storyText').value='';
tw.document.getElementById('timelinePublish').click();
assert.ok(tw.document.getElementById('sheet').classList.contains('open'));
assert.equal(tw.document.getElementById('notice').textContent,tw.__copy('writeFirst'));
tw.document.getElementById('dateInput').value='';
tw.document.getElementById('timelinePublish').click();
assert.ok(tw.document.getElementById('editModal').classList.contains('open'));
assert.equal(tw.document.getElementById('notice').textContent,tw.__copy('addDate'));
assert.deepEqual(tellErrors,[]);tellDom.window.close();
process.stdout.write('DOM timeline handoff: passed (canvas mocked; visual/browser QA remains open)\n');
