import {createStoryEditor} from './story-editor.js';
import {chooseTime,checkedTime,installDateStyle} from './date-picker.js';
import {timelineStories,timeLabel} from './dates.browser.js';
export function moveOrder(stories,id,targetMs){
  const ordered=timelineStories(stories).filter(s=>s.id!==id),left=ordered.filter(s=>s.displayMs<=targetMs).at(-1),right=ordered.find(s=>s.displayMs>targetMs);
  const a=left?.timelineOrder??left?.postedAt??left?.createdAt??0,b=right?.timelineOrder??right?.postedAt??right?.createdAt??(a+2);
  return Number.isFinite(a)&&Number.isFinite(b)?(a+b)/2:Date.now();
}
export async function moveStory(storage,id,time,targetMs){
  const story=await storage.story(id);if(!story)throw Error('Dit verhaal is niet meer beschikbaar.');checkedTime(time);
  const before={date:story.date,eventTime:story.eventTime,datePrecision:story.datePrecision,timelineOrder:story.timelineOrder};
  const saved=await storage.save({...story,...time,timelineOrder:moveOrder((await storage.stories()).filter(s=>time.eventTime?s.eventTime?.season===time.eventTime.season&&s.eventTime?.year===time.eventTime.year:s.date===time.date),id,targetMs)});return {saved,before};
}
export function installTimelineActions({runtime,storage,exclusive,notice}){
  installDateStyle();const menu=document.createElement('dialog');menu.id='freeStoryMenu';menu.setAttribute('aria-label','Verhaalacties');menu.innerHTML='<button class="free-menu-dismiss" type="button" aria-label="Verhaalmenu sluiten">×</button><button data-action="edit">Bewerken</button><button data-action="photo">Foto toevoegen</button><button data-action="delete">Verwijderen</button>';document.body.append(menu);
  const style=document.createElement('style');style.textContent='#freeStoryMenu{position:fixed;inset:auto;margin:0;width:230px;max-width:calc(100vw - 24px);padding:8px;border:1px solid #ffffff80;background:#f7faf9ed;border-radius:18px;box-shadow:0 8px 30px #0003;backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px)}#freeStoryMenu::backdrop{background:transparent}#freeStoryMenu button[data-action]{display:block;width:100%;margin:0;text-align:left;background:transparent;padding:13px 12px;font-weight:600}#freeStoryMenu button[data-action=delete]{color:#b63b3b}#freeStoryMenu .free-menu-dismiss{display:none}#freeMoveCard{position:fixed;z-index:1000;left:50%;top:38%;width:180px;height:220px;border-radius:18px;background:#173851 center/cover;color:white;box-shadow:0 12px 36px #0008;pointer-events:none;transform:translate(-50%,-50%);display:flex;align-items:end;padding:14px;box-sizing:border-box}#freeMoveTarget{position:fixed;z-index:1001;top:24%;left:50%;transform:translateX(-50%);border-radius:16px;background:white;color:#173851;padding:8px 14px;font:600 16px system-ui;pointer-events:none}#freeMoveUndo{position:fixed;z-index:100;bottom:130px;left:50%;transform:translateX(-50%);background:#173851;color:white;border:1px solid white;padding:14px;border-radius:18px;font:16px system-ui}';document.head.append(style);
  let undoTimer,gesture=null,holdTimer,card,label,raf,lifting=false;
  const surface=document.getElementById('memoryStoryScroll');
  function position(){const frame=document.querySelector('.app')?.getBoundingClientRect(),timeline=document.querySelector('.timeline')?.getBoundingClientRect(),right=Math.max(12,innerWidth-(frame?.right||innerWidth)+18),top=(timeline?.bottom||176)+58;const button=document.getElementById('freeEdit');button.style.right=right+'px';button.style.top=top+'px';menu.style.right=right+'px';menu.style.top=(top+48)+'px';}function open(){position();menu.showModal();}position();window.addEventListener('resize',position);menu.querySelector('.free-menu-dismiss').onclick=()=>menu.close();menu.addEventListener('click',e=>{if(e.target===menu){const r=menu.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)menu.close();}});document.getElementById('freeEdit').textContent='⋯';document.getElementById('freeEdit').setAttribute('aria-label','Verhaalmenu');document.getElementById('freeEdit').onclick=open;
  const more=document.querySelector('.more')?.closest('button');more?.addEventListener('click',e=>{e.stopImmediatePropagation();document.getElementById('freeStorageInfo').showModal();},true);
  async function refresh(id,keepCenter=false){const previousCenter=runtime.centerMs();for(const story of timelineStories((await storage.stories()).filter(s=>s.status==='published'))){const old=runtime.findMemory({storyId:story.id});if(old)runtime.registerMemory({...old,at:new Date(story.displayMs).toISOString(),ms:story.displayMs,timeLabel:timeLabel(story),datePrecision:story.datePrecision,story:story.title||story.storyText.slice(0,90),fullStory:story.storyText,audioId:story.audioId||'',editRevision:story.updatedAt});}const memory=runtime.findMemory({storyId:id});runtime.setCenter(keepCenter?previousCenter:memory.ms);runtime.writeMemory(memory);runtime.draw();}
  async function propose(id,targetMs){const date=new Date(Math.min(targetMs,Date.now())).toISOString().slice(0,10);const time=await chooseTime({date},'Wanneer gebeurde dit verhaal op de nieuwe plek?');if(!time){const original=runtime.findMemory({storyId:id});if(original){runtime.setCenter(original.ms);runtime.draw();}return;}const result=await exclusive(()=>moveStory(storage,id,time,targetMs));await refresh(id);document.getElementById('freeMoveUndo')?.remove();clearTimeout(undoTimer);const undo=document.createElement('button');undo.id='freeMoveUndo';undo.textContent='Verplaatst · Ongedaan maken';document.body.append(undo);undo.onclick=async()=>{undo.disabled=true;try{await exclusive(async()=>{const current=await storage.story(id);await storage.save({...current,...result.before});});await refresh(id);undo.remove();}catch(e){undo.disabled=false;notice(e.message);}};undoTimer=setTimeout(()=>undo.remove(),15000);}
  const editor=createStoryEditor({storage,exclusive,onSaved:async story=>{await refresh(story.id,runtime.findMemory({storyId:story.id})?.timeLabel===timeLabel(story));window.dispatchEvent(new Event('talera-story-edited'));}});
  menu.querySelectorAll('[data-action]').forEach(button=>button.onclick=async()=>{
    menu.close();const memory=runtime.currentMemory();
    try{
      if(button.dataset.action==='edit'||button.dataset.action==='photo')await editor.open(memory.storyId,{focusPhotos:button.dataset.action==='photo'});
      if(button.dataset.action==='delete'){
        const confirm=document.createElement('dialog');confirm.className='free-time-dialog';confirm.innerHTML='<h2>Dit verhaal verwijderen?</h2><p>Je oorspronkelijke foto’s op je telefoon blijven behouden.</p><button data-no>Annuleren</button><button data-yes>Verwijderen</button>';document.body.append(confirm);
        confirm.querySelector('[data-no]').onclick=()=>confirm.remove();confirm.querySelector('[data-yes]').onclick=async()=>{try{await exclusive(()=>storage.delete(memory.storyId));location.href='/';}catch(e){confirm.querySelector('p').textContent=e.message;}};confirm.showModal();
      }
    }catch(error){notice(error.message);}
  });
  if(new URLSearchParams(location.hash.slice(1)).get('edit')==='1')setTimeout(()=>editor.open(runtime.currentMemory().storyId).catch(error=>notice(error.message)),0);
  function clean(){clearTimeout(holdTimer);cancelAnimationFrame(raf);card?.remove();label?.remove();card=label=null;}
  function updateLabel(){label.textContent=new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short',year:'numeric'}).format(new Date(gesture.target));}
  function pan(){if(!gesture?.active)return;const width=innerWidth,edge=gesture.x<width*.18?-1:gesture.x>width*.82?1:0;if(edge){const range=runtime.visibleBounds(),delta=(range[1]-range[0])*.004*edge;runtime.setCenter(runtime.centerMs()+delta);gesture.target=Math.min(runtime.centerMs(),Date.now());runtime.draw();updateLabel();}raf=requestAnimationFrame(pan);}
  document.addEventListener('pointerdown',e=>{if(!surface?.contains(e.target)||e.target.closest('button,a,input,textarea')||e.button>0)return;gesture={id:e.pointerId,startX:e.clientX,startY:e.clientY,x:e.clientX,target:runtime.centerMs(),storyId:runtime.currentMemory().storyId,active:false};holdTimer=setTimeout(()=>{if(!gesture)return;gesture.active=true;lifting=true;surface.dispatchEvent(new PointerEvent('pointercancel',{bubbles:true,pointerId:gesture.id}));lifting=false;card=document.createElement('div');card.id='freeMoveCard';card.style.backgroundImage='url("'+runtime.currentMemory().image.replaceAll('"','%22')+'")';card.textContent=runtime.currentMemory().story;label=document.createElement('div');label.id='freeMoveTarget';document.body.append(card,label);updateLabel();pan();},1000);},true);
  document.addEventListener('pointermove',e=>{if(!gesture||gesture.id!==e.pointerId)return;if(!gesture.active){if(Math.hypot(e.clientX-gesture.startX,e.clientY-gesture.startY)>8){clean();gesture=null;}return;}e.preventDefault();e.stopImmediatePropagation();const range=runtime.visibleBounds();runtime.setCenter(runtime.centerMs()+(e.clientX-gesture.x)/innerWidth*(range[1]-range[0]));gesture.x=e.clientX;gesture.target=Math.min(runtime.centerMs(),Date.now());card.style.left=e.clientX+'px';runtime.draw();updateLabel();},{capture:true,passive:false});
  document.addEventListener('pointerup',e=>{if(!gesture||gesture.id!==e.pointerId)return;const current=gesture;gesture=null;clean();if(current.active){e.preventDefault();e.stopImmediatePropagation();propose(current.storyId,current.target).catch(e=>notice(e.message));}},true);
  document.addEventListener('pointercancel',e=>{if(gesture&&!lifting){gesture=null;clean();}},true);window.addEventListener('pagehide',()=>{gesture=null;clean();clearTimeout(undoTimer);});
}
