export const taleraTellStyle = String.raw`
.talera-tell{position:fixed;inset:0;z-index:9000;display:none;background:#0F2747;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.talera-tell.open{display:block}.talera-tell-inner{position:absolute;inset:0;display:flex;flex-direction:column;background:linear-gradient(180deg,#18334f,#41657d 48%,#0f2747)}.talera-tell-head{display:flex;align-items:center;justify-content:space-between;padding:max(18px,env(safe-area-inset-top)) 20px 10px}.talera-tell-brand{font-size:12px;letter-spacing:.28em;font-weight:800}.talera-tell-close{border:1px solid rgba(255,255,255,.35);background:rgba(255,255,255,.08);color:#fff;border-radius:999px;width:44px;height:44px;font-size:24px}.talera-tell-body{flex:1;min-height:0;display:flex;flex-direction:column;align-items:center;padding:12px 24px calc(28px + env(safe-area-inset-bottom));overflow:auto}.talera-tell-preview{width:min(82vw,420px);height:min(43vh,420px);border-radius:24px;overflow:hidden;background:rgba(255,255,255,.08);display:flex;align-items:center;justify-content:center}.talera-tell-preview img{display:block;width:100%;height:100%;object-fit:contain}.talera-tell-preview img[hidden]{display:none}.talera-tell-empty{text-align:center;padding:24px;font-weight:750;font-size:22px;line-height:1.12}.talera-tell-empty small{display:block;margin-top:10px;font-size:14px;font-weight:450;opacity:.75;line-height:1.4}.talera-tell-actions{display:flex;gap:16px;margin:22px 0}.talera-tell-round{width:68px;height:68px;border-radius:50%;border:1px solid rgba(255,255,255,.5);background:#F7F4EF;color:#0F2747;font-size:27px;font-weight:800}.talera-tell-round.recording{background:#E7A98B}.talera-tell-status{min-height:24px;text-align:center;font-size:14px;opacity:.9}.talera-tell-audio{width:min(82vw,420px);margin-top:10px}.talera-tell-save{margin-top:18px;min-height:48px;border:0;border-radius:999px;padding:0 24px;background:#F7F4EF;color:#0F2747;font-weight:800;font-size:15px}.talera-tell-save:disabled{opacity:.45}.talera-tell-file{position:absolute;inset:0;width:100%;height:100%;opacity:0;cursor:pointer}.talera-pick{position:relative;display:flex;align-items:center;justify-content:center;overflow:hidden}
`;
export const taleraTellScript = String.raw`
(()=>{

 const tell=document.querySelector('.tell');if(!tell)return;
 const root=document.createElement('section');root.className='talera-tell';root.setAttribute('aria-label','Nieuwe herinnering');
 root.innerHTML='<div class="talera-tell-inner"><header class="talera-tell-head"><strong class="talera-tell-brand">TALERA</strong><button class="talera-tell-close" type="button" aria-label="Sluiten">×</button></header><div class="talera-tell-body"><div class="talera-tell-preview"><div class="talera-tell-empty">Kies een foto<small>Daarna kun je je herinnering inspreken.</small></div><img hidden alt="Gekozen foto"></div><div class="talera-tell-actions"><label class="talera-tell-round talera-pick" aria-label="Foto kiezen">＋<input class="talera-tell-file" type="file" accept="image/*"></label><button class="talera-tell-round talera-record" type="button" aria-label="Opname starten">●</button></div><div class="talera-tell-status" aria-live="polite">Kies eerst een foto en vertel daarna je herinnering.</div><audio class="talera-tell-audio" controls hidden></audio><button class="talera-tell-save" type="button" disabled>Bewaar herinnering</button></div></div>';
 document.body.appendChild(root);
 const close=root.querySelector('.talera-tell-close'),input=root.querySelector('.talera-tell-file'),pick=root.querySelector('.talera-pick'),record=root.querySelector('.talera-record'),img=root.querySelector('img'),empty=root.querySelector('.talera-tell-empty'),status=root.querySelector('.talera-tell-status'),audio=root.querySelector('audio'),save=root.querySelector('.talera-tell-save');
 let photoUrl='',recorder=null,chunks=[],audioUrl='',stream=null,photoFile=null,audioBlob=null; window.__taleraTellOpen=open;
 function cleanupStream(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
 function open(){root.classList.add('open')}function shut(){cleanupStream();root.classList.remove('open')}
 tell.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();open()},true);close.addEventListener('click',shut);input.addEventListener('click',()=>{status.textContent='Fotobibliotheek wordt geopend…'});
 input.addEventListener('change',()=>{const file=input.files&&input.files[0];if(!file){status.textContent='Er is geen foto gekozen.';return}photoFile=file;status.textContent='Foto wordt geladen…';const reader=new FileReader();reader.onload=()=>{photoUrl=String(reader.result||'');img.onload=()=>{img.hidden=false;empty.hidden=true;status.textContent='Foto gekozen. Je kunt nu je herinnering inspreken.';save.disabled=false};img.onerror=()=>{status.textContent='Deze foto kon niet worden geopend. Probeer een andere foto.'};img.src=photoUrl;img.removeAttribute('hidden')};reader.onerror=()=>{status.textContent='De gekozen foto kon niet worden gelezen.'};reader.readAsDataURL(file)});
 let micBusy=false;record.addEventListener('click',async()=>{if(micBusy)return;if(recorder&&recorder.state==='recording'){record.disabled=true;status.textContent='Opname wordt afgerond…';recorder.stop();return}if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia||!window.MediaRecorder){status.textContent='Opnemen wordt door deze browser niet ondersteund.';return}micBusy=true;record.disabled=true;record.classList.add('recording');status.textContent='Microfoon wordt gestart…';try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};recorder.onstop=()=>{const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});audioBlob=blob;if(!blob.size){status.textContent='Er is geen audio opgenomen. Probeer opnieuw.';cleanupStream();return}if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=URL.createObjectURL(blob);audio.src=audioUrl;audio.hidden=false;record.classList.remove('recording');record.disabled=false;micBusy=false;record.textContent='●';status.textContent='Opname klaar. Luister hem terug of neem opnieuw op.';cleanupStream()};recorder.start();record.disabled=false;micBusy=false;record.classList.add('recording');record.textContent='■';status.textContent='Opname loopt… tik op stop wanneer je klaar bent.'}catch(err){cleanupStream();micBusy=false;record.disabled=false;record.classList.remove('recording');record.textContent='●';status.textContent=err&&err.name==='NotAllowedError'?'Microfoontoegang is niet toegestaan. Geef TALERA toegang in je browserinstellingen.':'De microfoon kon niet worden gestart.'}});
 save.addEventListener('click',()=>{status.textContent=photoFile?(audioBlob?'Foto en opname staan klaar om te bewaren.':'Foto staat klaar. Je kunt ook nog een verhaal inspreken.'):'Kies eerst een foto.'});
})();
`;
